import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {scryptSync} from 'node:crypto';import {openDatabase} from '../server/database.mjs';import {makeServer} from '../server/http.mjs';
const dir=mkdtempSync('./test-data-'),salt='ab'.repeat(16),password='test-only-password-not-a-deployment-secret';const passwordHash='scrypt:'+salt+':'+scryptSync(password,salt,64).toString('hex');const origin='http://127.0.0.1:3000';
let DB,server,base;async function start(){DB=openDatabase(dir+'/site.sqlite');server=makeServer({DB,origin,username:'admin',passwordHash});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port}async function stop(){await new Promise(r=>server.close(r));DB.close()}
const auth={Authorization:'Basic '+Buffer.from('admin:'+password).toString('base64')};const get=(p,h={})=>fetch(base+p,{headers:h});const put=(settings,revision,extra={})=>fetch(base+'/api/admin/settings',{method:'PUT',headers:{...auth,'Content-Type':'application/json','X-Admin-Request':'1',Origin:origin,...extra},body:JSON.stringify({settings,revision})});
try{await start();assert.equal((await get('/')).status,200);assert.equal((await get('/game/neon-drift')).status,200);assert.equal((await get('/category/puzzle')).status,200);assert.equal((await get('/admin')).status,401);assert.equal((await get('/api/admin/settings',{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'owner@example.com'})).status,401);assert.equal((await get('/admin',{Authorization:'Basic '+Buffer.from('admin:wrong').toString('base64')})).status,401);assert.equal((await get('/admin',auth)).status,200);
let data=await (await get('/api/admin/settings',auth)).json();let settings={...data.settings,siteName:'Test Arcade & Friends'};assert.equal((await put(settings,0,{Origin:'https://evil.example'})).status,403);assert.equal((await put(settings,0)).status,200);assert.equal((await put(settings,0)).status,409);assert.equal((await put({...settings,publisher:'bad'},1)).status,400);assert.equal((await put({...settings,adsEnabled:true},1)).status,400);
await stop();await start();data=await (await get('/api/admin/settings',auth)).json();assert.equal(data.settings.siteName,settings.siteName);assert.equal(data.revision,1);assert.match(await (await get('/')).text(),/Test Arcade &amp; Friends/);assert.match(await (await get('/robots.txt')).text(),/Disallow: \//);assert.equal((await (await get('/sitemap.xml')).text()).match(/<url>/g).length,132);assert.equal((await get('/data/site.sqlite')).status,404);assert.equal((await get('/.env')).status,404);
settings={...settings,adsEnabled:true,adsApproved:true,publisher:'ca-pub-1234567890123456',slot:'12345',cmpUrl:'https://fundingchoicesmessages.google.com/i/pub-1234567890123456?ers=1'};assert.equal((await put(settings,1)).status,200);assert.match(await (await get('/')).text(),/id="siteAd"/);assert.ok(!(await (await get('/game/neon-drift')).text()).includes('id="siteAd"'));assert.match(await (await get('/ads.txt')).text(),/google.com, pub-1234567890123456, DIRECT/);
const oversized=await fetch(base+'/api/admin/settings',{method:'PUT',headers:auth,body:'a'.repeat(17000)});assert.equal(oversized.status,413);
console.log('PASS: real HTTP routes; password login; forged-header rejection; CSRF; revision conflicts; SQLite restart persistence; SEO; ads validation and gameplay exclusion; private file isolation; request limits.');
}finally{if(server?.listening)await stop();rmSync(dir,{recursive:true,force:true})}
