'use strict';
const $=id=>document.getElementById(id);
const originalGames=[
{id:'neon-drift',title:'Neon Drift',category:'Racing',engine:'drift',art:'drift',tag:'FEATURED',meta:'Dodge. Drive. Repeat.',instructions:'Use the left and right arrow keys, A / D, or the on-screen buttons to change lanes. On a touchscreen, tap either side of the track. Avoid the pink cars for as long as you can. Space pauses the game.'},
{id:'orbit-breaker',title:'Orbit Breaker',category:'Arcade',engine:'breakout',art:0,tag:'HOT PICK',meta:'Find your flow',instructions:'Move your mouse or finger across the game to guide the paddle. You can also use the arrow keys or buttons. Bounce the ball to break all 40 blocks. Keep it from falling below the paddle.'},
{id:'2048',title:'2048',category:'Puzzle',engine:'merge',art:2,tag:'BRAIN FOOD',meta:'Merge your way to 2048',instructions:'Use arrow keys, swipe on the board, or tap the direction buttons. Matching tiles merge when they meet. Each move adds a new tile. Reach 2048, then keep playing if you like.'},
{id:'neon-snake',title:'Neon Snake',category:'Arcade',engine:'snake',art:1,tag:'CLASSIC REMIX',meta:'One more bite',instructions:'Use arrow keys, WASD, swipe gestures, or the direction buttons. Eat the pink squares to grow. Avoid the walls and your own tail. Each bite earns 10 points.'},
{id:'memory-pop',title:'Memory Pop',category:'Puzzle',engine:'memory',art:3,tag:'NEW',meta:'A little memory magic',instructions:'Flip two cards at a time to find matching symbols. Clear all eight pairs. Each pair earns 100 points; missed pairs cost 5 points. Fewer moves mean a higher score.'},
{id:'quick-tap',title:'Quick Tap',category:'Arcade',engine:'reaction',art:4,tag:'QUICK BREAK',meta:'How fast are your reflexes?',instructions:'Tap to begin, then wait for the panel to turn green. Tap as quickly as possible after it changes. Tapping early means a retry. Your fastest time in milliseconds is your best score.'},
{id:'tic-tac-toe',title:'Tic Tac Toe',category:'Classic',engine:'tic',art:5,tag:'2 PLAYERS',meta:'Bring a friend',instructions:'Two players share this device. Take turns placing X and O. Get three in a row, column, or diagonal to win. X always starts. Press Restart for a new round.'},
{id:'slide-quest',title:'Slide Quest',category:'Puzzle',engine:'slide',art:2,tag:'NEW',meta:'Every move matters',instructions:'Tap a numbered tile next to the empty square to slide it. Arrange the tiles in order: 1, 2, 3 / 4, 5, 6 / 7, 8, empty. Every starting puzzle is solvable. Fewer moves earn more points.'}
];
const defaults=[...(window.GAMEMONETIZE_CATALOG||[]),...(window.GAMEPIX_CATALOG||[]),...originalGames];
function read(key,fallback){try{const v=JSON.parse(localStorage.getItem('playnova-'+key));return v??fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem('playnova-'+key,JSON.stringify(value))}catch{toast('Your browser could not save this change.')}}
const BRAND=window.__SITE__.siteName;
const games=window.__CATALOG__;
let favorites=read('favorites',[]),recent=read('recent',[]),bests=read('bests',{});if(!Array.isArray(favorites))favorites=[];if(!Array.isArray(recent))recent=[];if(!bests||typeof bests!=='object'||Array.isArray(bests))bests={};
let view='home',category='All',query='',current=null,engine=null,paused=false,toastTimer,visibleLimit=24,providerFilter='All';
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2300)}
function artStyle(g){if(g.art==='drift')return 'background-image:url(/assets/drift.webp);background-size:cover;background-position:center';return 'background-position:'+((g.art%3)*50)+'% '+(g.art>2?100:0)+'%'+(g.id==='slide-quest'?';filter:hue-rotate(180deg)':'')}
function coverImage(g){
 let src=g.thumbnail,extra='';
 if(g.provider==='GamePix'){
  const base=new URL(g.thumbnail);base.searchParams.set('w','640');src=base.href;
  const hi=new URL(src);hi.searchParams.set('w','960');
  extra=` srcset="${esc(src)} 640w, ${esc(hi.href)} 960w" sizes="(max-width:560px) calc((100vw - 44px)/2), (max-width:800px) calc((100vw - 74px)/3), (max-width:1150px) calc((100vw - 279px)/3), (max-width:1792px) calc((100vw - 345px)/4), 355px"`;
 }
 return `<img class="cover-art cover-image" src="${esc(src)}"${extra} data-fallback="${esc(g.thumbnail)}" alt="" loading="lazy" decoding="async" referrerpolicy="strict-origin-when-cross-origin">`;
}
function card(g){const saved=favorites.includes(g.id);return `<article class="game-card"><a class="cover-link" href="/game/${g.id}" aria-label="Play ${esc(g.title)}">${g.provider?coverImage(g):`<div class="cover-art" style="${artStyle(g)}"></div>`}<span class="game-badge ${g.tag==='NEW'?'new':''}">${g.tag}</span></a><button class="favorite-button ${saved?'saved':''}" data-save="${g.id}" aria-label="${saved?'Remove':'Add'} ${esc(g.title)} ${saved?'from':'to'} favorites" aria-pressed="${saved}">${saved?'♥':'♡'}</button><div class="card-info"><h3><a href="/game/${g.id}">${esc(g.title)}</a></h3><span>↗</span></div><div class="card-meta"><span>${g.category}</span><i>·</i><span>${g.provider?esc(g.provider):g.id==='tic-tac-toe'?'2 players':'Original'}</span></div></article>`}
function render(){let list=games.filter(g=>!g.hidden);if(providerFilter!=='All')list=list.filter(g=>(g.provider||'Originals')===providerFilter);if(view==='favorites')list=list.filter(g=>favorites.includes(g.id));if(view==='recent')list=recent.map(id=>games.find(g=>g.id===id&&!g.hidden)).filter(Boolean);if(category!=='All')list=list.filter(g=>g.category===category);if(query)list=list.filter(g=>(g.title+' '+g.category+' '+g.meta).toLowerCase().includes(query.toLowerCase()));$('gameGrid').innerHTML=list.slice(0,visibleLimit).map(card).join('');$('loadMore').hidden=list.length<=visibleLimit;$('loadMore').textContent='Show more games ('+Math.max(0,list.length-visibleLimit)+' more)';$('gameCount').textContent=list.length+' game'+(list.length===1?'':'s');$('favCount').textContent=favorites.filter(id=>games.some(g=>g.id===id&&!g.hidden)).length;$('homeFeatures').hidden=view!=='home'||category!=='All'||!!query;$('bottomBanner').hidden=view!=='home'||!!query;$('emptyState').hidden=!!list.length;$('emptyText').textContent=query?'No matches for “'+query+'”. Try a different search.':view==='favorites'?'Tap the heart on any game to save it here.':view==='recent'?'Play your first game and it will appear here.':'Try another category.';$('pageTitle').textContent=view==='favorites'?'Your favorite escapes.':view==='recent'?'Pick up the good times.':category!=='All'?category+' games, your way.':'What are we playing?';$('sectionTitle').textContent=query?'Search results':view==='favorites'?'Saved for another round':view==='recent'?'Recently played':category!=='All'?'A little more '+category.toLowerCase():'Find your next obsession ✦';$('sectionSubtitle').textContent=view==='home'?'GamePix, GameMonetize, and original games. Zero downloads.':'Saved on this device, ready when you are.';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view&&category==='All'));document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category===category));document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===category));}
function save(id){if(favorites.includes(id)){favorites=favorites.filter(x=>x!==id);toast('Removed from favorites')}else{favorites.push(id);toast('Saved to your favorites')}write('favorites',favorites);render();syncSave()}
function syncSave(){if(!current)return;const saved=favorites.includes(current.id);$('saveGame').textContent=saved?'♥ Saved':'♡ Save game';$('saveGame').classList.toggle('saved',saved);$('saveGame').ariaPressed=String(saved)}
function setView(next,cat='All'){view=next;category=cat;query='';visibleLimit=24;providerFilter='All';$('providerFilter').value='All';$('search').value='';$('sidebar').classList.remove('open');render();if(location.hash.startsWith('#game/'))location.hash='home'}
function surprise(){const list=games.filter(g=>!g.hidden);if(!list.length){toast('Enable a game in Customize first.');return}location.href='/game/'+list[Math.floor(Math.random()*list.length)].id}
function cleanup(){if(engine){engine.destroy();engine=null}$('playArea').classList.remove('external-play-area');paused=false;$('pauseBtn').textContent='Ⅱ Pause'}
function togglePause(){if(!engine?.pause)return;paused=engine.pause();$('pauseBtn').textContent=paused?'▶ Resume':'Ⅱ Pause'}
function startGame(){cleanup();$('playArea').replaceChildren();$('score').textContent='0';$('gameStatus').textContent='';$('pauseBtn').hidden=!['drift','snake','breakout'].includes(current.engine);engine=PlaynovaGames[current.engine]({area:$('playArea'),game:current,status:t=>$('gameStatus').textContent=t,score:n=>{ $('score').textContent=n+(current.engine==='reaction'?' ms':'');const prev=Number(bests[current.id])||0;if(current.engine==='reaction'?(!prev||n<prev):n>prev){bests[current.id]=n;write('bests',bests);$('best').textContent=n+(current.engine==='reaction'?' ms':'')}},togglePause});}
function openGame(id){const g=games.find(g=>g.id===id&&!g.hidden);if(!g){toast('That game is not available.');location.hash='home';return}cleanup();current=g;recent=[id,...recent.filter(x=>x!==id)].slice(0,20);write('recent',recent);$('gameTitle').textContent=g.title;$('gameCategory').textContent=g.category.toUpperCase()+' · '+(g.provider?g.provider.toUpperCase():g.engine==='tic'?'2 PLAYERS':BRAND.toUpperCase()+' ORIGINAL');$('gameInstructions').textContent=g.instructions;const external=!!g.provider;document.querySelectorAll('.scorebar > span').forEach(el=>el.hidden=external);$('restartBtn').textContent=external?'↻ Reload game':'↻ Restart';$('providerInfo').textContent=external?'This game is provided by '+g.provider+' and may contain ads. Progress, scores, and consent choices are handled inside the game.':'Play free, right in your browser. Your best score is saved on this device.';$('score').textContent='0';$('best').textContent=(bests[id]||0)+(g.engine==='reaction'?' ms':'');$('relatedGames').innerHTML=games.filter(x=>!x.hidden&&x.id!==id).slice(0,4).map(x=>`<a href="/game/${x.id}">${esc(x.title)} ↗</a>`).join('');syncSave();$('pauseBtn').hidden=true;$('gameStatus').textContent='';$('playArea').innerHTML=`<div class="game-intro"><span class="intro-symbol">✦</span><h3>${esc(g.title)}</h3><p>${esc(g.instructions)}</p>${g.provider?'<p class="provider-notice">Hosted by '+esc(g.provider)+'. May include advertising and third-party cookies. Press Play now to load the game.</p>':''}<button class="primary" id="startGameBtn">▶ Play now</button></div>`;$('startGameBtn').onclick=startGame;if(!$('gameDialog').open)$('gameDialog').showModal();$('gameDialog').scrollTop=0;document.title=g.title+' — '+BRAND;render()}
function closeGame(){if(window.__PAGE__?.gameId){location.href='/';return}cleanup();if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});$('gameDialog').close();current=null;document.title=BRAND+' — '+window.__SITE__.tagline;if(location.hash.startsWith('#game/'))history.replaceState(null,'','#home');render()}
function route(){if(location.hash.startsWith('#game/'))openGame(location.hash.slice(6));else{if($('gameDialog').open)closeGame();if(location.hash==='#home')setView('home')}}
function showInfo(html){$('infoContent').innerHTML=html;$('infoDialog').showModal()}
$('search').addEventListener('input',e=>{query=e.target.value;visibleLimit=24;render()});document.addEventListener('click',e=>{const saveBtn=e.target.closest('[data-save]');if(saveBtn)save(saveBtn.dataset.save);const v=e.target.closest('[data-view]');if(v)setView(v.dataset.view);const cat=e.target.closest('[data-category]');if(cat)location.href='/category/'+cat.dataset.category.toLowerCase();const f=e.target.closest('[data-filter]');if(f){location.href=f.dataset.filter==='All'?'/':'/category/'+f.dataset.filter.toLowerCase()}});
['surpriseBtn','surpriseSide','quickPlay'].forEach(id=>$(id).onclick=surprise);$('favoriteTop').onclick=()=>setView('favorites');$('resetFilters').onclick=()=>setView('home');$('menuBtn').onclick=()=>{$('sidebar').classList.toggle('open');$('menuBtn').ariaExpanded=String($('sidebar').classList.contains('open'))};$('closeGame').onclick=closeGame;$('gameDialog').addEventListener('cancel',e=>{e.preventDefault();closeGame()});$('gameDialog').addEventListener('close',cleanup);$('restartBtn').onclick=()=>{if(current)startGame()};$('pauseBtn').onclick=togglePause;$('saveGame').onclick=()=>{if(current)save(current.id)};
$('fullscreenBtn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('gameDialog').requestFullscreen)await $('gameDialog').requestFullscreen();else toast('Fullscreen is not supported in this browser.')}catch{toast('Fullscreen is not available here.')}};
$('closeInfo').onclick=()=>$('infoDialog').close();$('aboutBtn').onclick=()=>showInfo('<p class="eyebrow">A LITTLE BREAK GOES A LONG WAY</p><h2>Welcome to '+esc(BRAND)+'.</h2><p>A collection of GamePix and GameMonetize browser games, plus eight original mini-games. No downloads, no account required. Just pick something that looks fun and play.</p><h3>Your privacy</h3><p>Favorites, recently played games, and scores are stored in this browser. They do not sync across devices. Our original mini-games include no advertising or analytics trackers. GamePix and GameMonetize games load only when you press Play now and may include advertising, cookies, and their own consent choices. Catalog images load from their providers when you browse. If enabled by the owner, this website uses Google AdSense on browsing pages after its consent check. Provider consent choices are separate. The site loads fonts from Google Fonts; your hosting provider may retain ordinary access logs.</p><h3>Something not working?</h3><p>Try restarting the game or refreshing the page. Modern Chrome, Firefox, Safari, and Edge are recommended. Tic Tac Toe is played by two people sharing one device.</p>');
$('profileBtn').onclick=()=>{showInfo(`<p class="eyebrow">YOUR CORNER OF THE ARCADE</p><h2>Hey, player.</h2><p>No login needed. Your collection lives right here on this device.</p><div class="stats"><div><b>${recent.length}</b><span>Games tried</span></div><div><b>${favorites.length}</b><span>Favorites</span></div><div><b>${Object.keys(bests).length}</b><span>Personal bests</span></div></div><button class="primary" id="viewCollection">View favorites ↗</button>`);$('viewCollection').onclick=()=>{$('infoDialog').close();setView('favorites')}};
$('providerFilter').onchange=e=>{providerFilter=e.target.value;visibleLimit=24;render()};
$('loadMore').onclick=()=>{visibleLimit+=24;render()};
$('gameGrid').addEventListener('error',e=>{const img=e.target;if(img.tagName==='IMG'){img.removeAttribute('srcset');if(img.dataset.fallback&&img.dataset.retried!=='true'){img.dataset.retried='true';img.src=img.dataset.fallback}else{img.hidden=true;img.parentElement.classList.add('image-unavailable');const label=document.createElement('span');label.className='image-fallback-label';label.textContent=img.parentElement.getAttribute('aria-label').replace(/^Play /,'');img.parentElement.append(label)}}},true);
window.addEventListener('hashchange',route);document.addEventListener('keydown',e=>{if(e.key==='/'&&!$('gameDialog').open&&!$('infoDialog').open&&document.activeElement.tagName!=='INPUT'){e.preventDefault();$('search').focus()}if(e.key==='Escape')$('sidebar').classList.remove('open')});render();route();

if(window.__PAGE__?.category){category=window.__PAGE__.category;render()}
if(window.__PAGE__?.gameId)openGame(window.__PAGE__.gameId);
