/* GamePix catalog snapshot. Rebuild using scripts/import-gamepix.py. */
window.GAMEPIX_CATALOG = [
  {
    "id": "gpx-737HCH",
    "providerId": "737HCH",
    "title": "Prism Match 3D",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Match 3",
    "description": "Dive into a mesmerizing 3D cube universe where vibrant prisms challenge your logic and timing. Rotate and explore intricately designed levels while relaxing your mind. Perfect your skills to conquer endless creative stages, offering a refreshing blend of relaxation and mental exercise.",
    "instructions": "Dive into a mesmerizing 3D cube universe where vibrant prisms challenge your logic and timing. Rotate and explore intricately designed levels while relaxing your mind. Perfect your skills to conquer endless creative stages, offering a refreshing blend of relaxation and mental exercise.",
    "url": "https://play.gamepix.com/prism-match-3d/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/prism-match-3d/cover/prism-match-3d.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-401685",
    "providerId": "401685",
    "title": "Drop Planets",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Puzzle",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/drop-planets/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/drop-planets/cover/drop-planets.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-5G91RE",
    "providerId": "5G91RE",
    "title": "Garden Master",
    "category": "Strategy",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Farming",
    "description": "Step into the shoes of a industrious gnome in Garden Master! Nurture your plants with care, fend off mischievous gophers, and gather golden seeds to unlock exciting upgrades. Cultivate a lush paradise and prove your gardening prowess in this delightful and challenging adventure.",
    "instructions": "Step into the shoes of a industrious gnome in Garden Master! Nurture your plants with care, fend off mischievous gophers, and gather golden seeds to unlock exciting upgrades. Cultivate a lush paradise and prove your gardening prowess in this delightful and challenging adventure.",
    "url": "https://play.gamepix.com/garden-master/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/garden-master/cover/garden-master.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-EE5DCF",
    "providerId": "EE5DCF",
    "title": "Defend the Castle",
    "category": "Strategy",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Strategy",
    "description": "Fortify your kingdom in Defend the Castle! Strategically build and upgrade defenses with gold and wood to resist relentless enemy waves. Deploy cunning tactics with cannons and archers. Can you protect the King and let your stronghold stand the test of time?",
    "instructions": "Fortify your kingdom in Defend the Castle! Strategically build and upgrade defenses with gold and wood to resist relentless enemy waves. Deploy cunning tactics with cannons and archers. Can you protect the King and let your stronghold stand the test of time?",
    "url": "https://play.gamepix.com/defend-the-castle/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/defend-the-castle/cover/defend-the-castle.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-A311T3",
    "providerId": "A311T3",
    "title": "Stack Rocket",
    "category": "Strategy",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Building",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/stack-rocket/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/stack-rocket/cover/stack-rocket.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-O1H119",
    "providerId": "O1H119",
    "title": "Nova Hop",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Hyper Casual",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/nova-hop/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/nova-hop/cover/nova-hop.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-B6BTZI",
    "providerId": "B6BTZI",
    "title": "Quarantine Zombies",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Zombie",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/quarantine-zombies/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/quarantine-zombies/cover/quarantine-zombies.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-1BA572",
    "providerId": "1BA572",
    "title": "Boost Balloon",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Casual",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/boost-balloon/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/boost-balloon/cover/boost-balloon.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-A97NE0",
    "providerId": "A97NE0",
    "title": "Billiards on Ice",
    "category": "Sports",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Sports",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/billiards-on-ice/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/billiards-on-ice/cover/billiards-on-ice.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-7DO9L8",
    "providerId": "7DO9L8",
    "title": "Combat Landing",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Airplane",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/combat-landing/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/combat-landing/cover/combat-landing.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-T59T15",
    "providerId": "T59T15",
    "title": "Vegan Quest",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Arcade",
    "description": "Guide your vegan hero through a cascade of food in Vegan Quest! Collect delicious vegan treats to boost your score, while dodging non-vegan pitfalls. With straightforward controls and ever-increasing challenges, this arcade adventure delivers endless entertainment, demanding precision and quick decision-making as obstacles intensify.",
    "instructions": "Guide your vegan hero through a cascade of food in Vegan Quest! Collect delicious vegan treats to boost your score, while dodging non-vegan pitfalls. With straightforward controls and ever-increasing challenges, this arcade adventure delivers endless entertainment, demanding precision and quick decision-making as obstacles intensify.",
    "url": "https://play.gamepix.com/vegan-quest/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/vegan-quest/cover/vegan-quest.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-M46I6",
    "providerId": "M46I6",
    "title": "Kobadoo Emojis",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Trivia",
    "description": "Kobadoo Emojis invites you into a delightful memory challenge with amusing emojis to sequence. As you advance, the complexity grows, enhancing your cognitive skills while you enjoy the easy controls. Focus, observe, and test your brain in this engaging and laughter-filled experience.",
    "instructions": "Kobadoo Emojis invites you into a delightful memory challenge with amusing emojis to sequence. As you advance, the complexity grows, enhancing your cognitive skills while you enjoy the easy controls. Focus, observe, and test your brain in this engaging and laughter-filled experience.",
    "url": "https://play.gamepix.com/kobadoo-emojis/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/kobadoo-emojis/cover/kobadoo-emojis.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-KKTTKS",
    "providerId": "KKTTKS",
    "title": "Skater Kitty",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Cats",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/skater-kitty/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/skater-kitty/cover/skater-kitty.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-9211YC",
    "providerId": "9211YC",
    "title": "Flag Memory Match",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Memory",
    "description": "Test your memory with Flag Memory Match, a vibrant educational challenge featuring flags from 98 countries. Flip cards to find matching pairs, earn points, and unlock six increasingly difficult levels. Sharpen your focus and precision to become a flag-matching pro in this entertaining and educational journey.",
    "instructions": "Test your memory with Flag Memory Match, a vibrant educational challenge featuring flags from 98 countries. Flip cards to find matching pairs, earn points, and unlock six increasingly difficult levels. Sharpen your focus and precision to become a flag-matching pro in this entertaining and educational journey.",
    "url": "https://play.gamepix.com/flag-memory-match/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/flag-memory-match/cover/flag-memory-match.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-68RO08",
    "providerId": "68RO08",
    "title": "Memory Cards",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Memory",
    "description": "Test your memory and cognitive skills with Memory Cards! Sequence through increasingly challenging levels by identifying and selecting cards in the correct order. Perfect for a brain workout, this captivating game ensures surprising twists and mental boosts as you advance through its intricate stages.",
    "instructions": "Test your memory and cognitive skills with Memory Cards! Sequence through increasingly challenging levels by identifying and selecting cards in the correct order. Perfect for a brain workout, this captivating game ensures surprising twists and mental boosts as you advance through its intricate stages.",
    "url": "https://play.gamepix.com/memory-cards/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/memory-cards/cover/memory-cards.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-1ESE05",
    "providerId": "1ESE05",
    "title": "Sumo Shove",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Fighting",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/sumo-shove/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/sumo-shove/cover/sumo-shove.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-H54UGT",
    "providerId": "H54UGT",
    "title": "Seat the Guests",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Puzzle",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/seat-the-guests/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/seat-the-guests/cover/seat-the-guests.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-6D6TBE",
    "providerId": "6D6TBE",
    "title": "Dodge the Bull",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Casual",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/dodge-the-bull/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/dodge-the-bull/cover/dodge-the-bull.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-32H7T2",
    "providerId": "32H7T2",
    "title": "Math Fight Club",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Math",
    "description": "Unleash your inner math warrior in Math Fight Club! Customize your character, solve challenging equations, and battle legendary opponents in the ring. Outsmart your foes with quick calculations, collect their masks, and rise to become the ultimate math champion. Can you conquer every math legend?",
    "instructions": "Unleash your inner math warrior in Math Fight Club! Customize your character, solve challenging equations, and battle legendary opponents in the ring. Outsmart your foes with quick calculations, collect their masks, and rise to become the ultimate math champion. Can you conquer every math legend?",
    "url": "https://play.gamepix.com/math-fight-club/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/math-fight-club/cover/math-fight-club.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-047891",
    "providerId": "047891",
    "title": "Merge Royal",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "2048",
    "description": "Dive into Merge Royal, where Solitaire strategy meets 2048 thrill. Effortlessly merge matching cards, aiming for higher numbers while unlocking dazzling visuals. Perfect for relaxing yet challenging gameplay that tests your logic and speed. Can you master the ultimate card puzzle adventure?",
    "instructions": "Dive into Merge Royal, where Solitaire strategy meets 2048 thrill. Effortlessly merge matching cards, aiming for higher numbers while unlocking dazzling visuals. Perfect for relaxing yet challenging gameplay that tests your logic and speed. Can you master the ultimate card puzzle adventure?",
    "url": "https://play.gamepix.com/merge-royal/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/merge-royal/cover/merge-royal.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-3R166",
    "providerId": "3R166",
    "title": "Kobadoo Numbers",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Memory",
    "description": "Strengthen your mind with Kobadoo Numbers, a captivating browser game. Challenge yourself to memorize increasingly difficult two-digit sequences and enhance your cognitive abilities in a fun way. Unlock the potential of your working memory as you improve your focus, attention, and mental agility while enjoying this addictive experience.",
    "instructions": "Strengthen your mind with Kobadoo Numbers, a captivating browser game. Challenge yourself to memorize increasingly difficult two-digit sequences and enhance your cognitive abilities in a fun way. Unlock the potential of your working memory as you improve your focus, attention, and mental agility while enjoying this addictive experience.",
    "url": "https://play.gamepix.com/kobadoo-numbers/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/kobadoo-numbers/cover/kobadoo-numbers.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-S5498",
    "providerId": "S5498",
    "title": "Kobadoo Shapes",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Trivia",
    "description": "Kobadoo Shapes challenges you to memorize and replicate sequences of vibrant shapes, enhancing your memory while delivering a rewarding mental workout. With its addictive mechanics and engaging visuals, this game invites players of all ages to relax and focus as difficulty ramps up across multiple levels.",
    "instructions": "Kobadoo Shapes challenges you to memorize and replicate sequences of vibrant shapes, enhancing your memory while delivering a rewarding mental workout. With its addictive mechanics and engaging visuals, this game invites players of all ages to relax and focus as difficulty ramps up across multiple levels.",
    "url": "https://play.gamepix.com/kobadoo-shapes/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/kobadoo-shapes/cover/kobadoo-shapes.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-O6650",
    "providerId": "O6650",
    "title": "My First 100 Words",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Educational",
    "description": " Immerse your child in \"My First 100 Words,\" a vibrant language adventure! They will explore multiple languages through playful interactions, spotting emojis while hearing correct pronunciations. With increasing challenges, they\u2019ll build vocabulary and cultural awareness, making learning a captivating journey. Watch them thrive as they start a multilingual quest!",
    "instructions": " Immerse your child in \"My First 100 Words,\" a vibrant language adventure! They will explore multiple languages through playful interactions, spotting emojis while hearing correct pronunciations. With increasing challenges, they\u2019ll build vocabulary and cultural awareness, making learning a captivating journey. Watch them thrive as they start a multilingual quest!",
    "url": "https://play.gamepix.com/my-100-first-words/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/my-100-first-words/cover/my-100-first-words.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-AON121",
    "providerId": "AON121",
    "title": "Ancient Armies vs Modern Weapons",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Battle",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/ancient-armies-vs-modern-weapons/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/ancient-armies-vs-modern-weapons/cover/ancient-armies-vs-modern-weapons.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-6312AO",
    "providerId": "6312AO",
    "title": "Trap the Convoy",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Tanks",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/trap-the-convoy/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/trap-the-convoy/cover/trap-the-convoy.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-08575E",
    "providerId": "08575E",
    "title": "Yenemy",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Io",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/yenemy-io/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/yenemy-io/cover/yenemy-io.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-60II0",
    "providerId": "60II0",
    "title": "Kobadoo Arithmetic",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Math",
    "description": "Sharpen your mind with Kobadoo Arithmetic, a captivating number challenge that enhances math skills and memory. Memorize sequences, calculate sums, and tackle increasingly complex levels. This scientifically designed game offers a simple yet stimulating experience that boosts cognitive abilities while keeping players engaged and entertained. ",
    "instructions": "Sharpen your mind with Kobadoo Arithmetic, a captivating number challenge that enhances math skills and memory. Memorize sequences, calculate sums, and tackle increasingly complex levels. This scientifically designed game offers a simple yet stimulating experience that boosts cognitive abilities while keeping players engaged and entertained. ",
    "url": "https://play.gamepix.com/kobadoo-arithmetic/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/kobadoo-arithmetic/cover/kobadoo-arithmetic.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-24A7L",
    "providerId": "24A7L",
    "title": "Kobadoo Flags",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Trivia",
    "description": "Test your flag knowledge with Kobadoo Flags, an addictive game that sharpens memory and boosts cognitive skills. Memorize flags as challenges intensify, making it both entertaining and enlightening. Perfect for flag enthusiasts and those eager to enhance mental performance while having fun. Dive into this captivating world of flags today!",
    "instructions": "Test your flag knowledge with Kobadoo Flags, an addictive game that sharpens memory and boosts cognitive skills. Memorize flags as challenges intensify, making it both entertaining and enlightening. Perfect for flag enthusiasts and those eager to enhance mental performance while having fun. Dive into this captivating world of flags today!",
    "url": "https://play.gamepix.com/kobadoo-flags/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/kobadoo-flags/cover/kobadoo-flags.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-G6H7RT",
    "providerId": "G6H7RT",
    "title": "War the Knights",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Battle",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/war-the-knights/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/war-the-knights/cover/war-the-knights.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-71S7D8",
    "providerId": "71S7D8",
    "title": "Bus Driver Simulator 3D",
    "category": "Strategy",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Simulation",
    "description": "Experience the thrill of Bus Driver Simulator 3D by navigating iconic cities, conquering diverse terrains, and mastering the art of bus driving. Choose between adrenaline-packed racing or relaxed free mode, and immerse yourself in authentic cityscapes with dynamic traffic and weather for a truly captivating driving adventure.",
    "instructions": "Experience the thrill of Bus Driver Simulator 3D by navigating iconic cities, conquering diverse terrains, and mastering the art of bus driving. Choose between adrenaline-packed racing or relaxed free mode, and immerse yourself in authentic cityscapes with dynamic traffic and weather for a truly captivating driving adventure.",
    "url": "https://play.gamepix.com/bus-driver-simulator-3d/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/bus-driver-simulator-3d/cover/bus-driver-simulator-3d.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-A710G1",
    "providerId": "A710G1",
    "title": "Three Cups Game",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Memory",
    "description": "Challenge your focus and memory with the Three Cups Game, where precision and strategy meet. Track the elusive cup hiding surprises as the pace intensifies with each level. Unveil secrets and celebrate each win in this deceptively simple, yet profoundly addictive mental adventure. How sharp is your attention?",
    "instructions": "Challenge your focus and memory with the Three Cups Game, where precision and strategy meet. Track the elusive cup hiding surprises as the pace intensifies with each level. Unveil secrets and celebrate each win in this deceptively simple, yet profoundly addictive mental adventure. How sharp is your attention?",
    "url": "https://play.gamepix.com/three-cups-game/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/three-cups-game/cover/three-cups-game.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-36DO1",
    "providerId": "36DO1",
    "title": "Body Drop 3D",
    "category": "Strategy",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Simulation",
    "description": "Experience hilarious ragdoll physics as a resilient crash test dummy in Body Drop 3D. Strategically aim and unleash powerful impacts with limited balls to maximize bone-crunching damage. Explore creative angles, unlock new scenarios, and enjoy the endless cycle of chaos and laughter. Can you outwit gravity?",
    "instructions": "Experience hilarious ragdoll physics as a resilient crash test dummy in Body Drop 3D. Strategically aim and unleash powerful impacts with limited balls to maximize bone-crunching damage. Explore creative angles, unlock new scenarios, and enjoy the endless cycle of chaos and laughter. Can you outwit gravity?",
    "url": "https://play.gamepix.com/body-drop-3d/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/body-drop-3d/cover/body-drop-3d.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-7300A",
    "providerId": "7300A",
    "title": "Parmesan Partisan",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Arcade",
    "description": "Step into the shoes of a cheese guardian in Parmesan Partisan, where you must fend off relentless rat invasions with blazing shotgun action. Balance strategy and speed to protect your cheesy realm, wield powerful upgrades, and prove yourself the ultimate hero in this thrilling defense adventure.",
    "instructions": "Step into the shoes of a cheese guardian in Parmesan Partisan, where you must fend off relentless rat invasions with blazing shotgun action. Balance strategy and speed to protect your cheesy realm, wield powerful upgrades, and prove yourself the ultimate hero in this thrilling defense adventure.",
    "url": "https://play.gamepix.com/parmesan-partisan/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/parmesan-partisan/cover/parmesan-partisan.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-00PO8",
    "providerId": "00PO8",
    "title": "Hoops & Fruits",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Drawing",
    "description": "Dive into the whimsical world of Hoops & Fruits, where your hoop-tossing skills meet colorful, fruity targets. Engage in addictive drag-and-drop gameplay with charming graphics and a captivating soundtrack, challenging you to master levels and score big by hooping multiple fruits at once.",
    "instructions": "Dive into the whimsical world of Hoops & Fruits, where your hoop-tossing skills meet colorful, fruity targets. Engage in addictive drag-and-drop gameplay with charming graphics and a captivating soundtrack, challenging you to master levels and score big by hooping multiple fruits at once.",
    "url": "https://play.gamepix.com/hoops-and-fruits/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/hoops-and-fruits/cover/hoops-and-fruits.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-E6O54",
    "providerId": "E6O54",
    "title": "Cerkio",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Ball",
    "description": "Cerkio invites you into a minimalist world where precision meets relaxation. Test your timing as you launch a ball into a target across 30 increasingly complex levels. With soothing music and intuitive one-touch controls, experience a challenging yet calming escape. Perfect your skills and master one-hand gameplay.",
    "instructions": "Cerkio invites you into a minimalist world where precision meets relaxation. Test your timing as you launch a ball into a target across 30 increasingly complex levels. With soothing music and intuitive one-touch controls, experience a challenging yet calming escape. Perfect your skills and master one-hand gameplay.",
    "url": "https://play.gamepix.com/cerkio/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/cerkio/cover/cerkio.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-2K4849",
    "providerId": "2K4849",
    "title": "Twin Peeks",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Hidden Object",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/twin-peeks/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/twin-peeks/cover/twin-peeks.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-ITTTN",
    "providerId": "ITTTN",
    "title": "Turbo Crash Test",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Stickman",
    "description": "Turbo Dismounting is a thrilling physics-based adventure where players create epic crashes. Propel your stickman through chaotic obstacles, earning rewards to unlock diverse vehicles and challenging levels. Revel in the havoc with unique replays, testing your skills in explosive, adrenaline-fueled gameplay.",
    "instructions": "Turbo Dismounting is a thrilling physics-based adventure where players create epic crashes. Propel your stickman through chaotic obstacles, earning rewards to unlock diverse vehicles and challenging levels. Revel in the havoc with unique replays, testing your skills in explosive, adrenaline-fueled gameplay.",
    "url": "https://play.gamepix.com/turbo-dismounting/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/turbo-dismounting/cover/turbo-dismounting.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-IE9OL",
    "providerId": "IE9OL",
    "title": "Gelatino",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Arcade",
    "description": "Guide a courageous popsicle on a cooling adventure in Gelatino! Swing past traps, snag ice cubes, and dodge bushels of blazing heat to extend your minty fresh expedition. Precise movement and on-the-fly strategy keep the popsicle intact as you zigzag through sun-soaked lands. Will you melt or prevail?",
    "instructions": "Guide a courageous popsicle on a cooling adventure in Gelatino! Swing past traps, snag ice cubes, and dodge bushels of blazing heat to extend your minty fresh expedition. Precise movement and on-the-fly strategy keep the popsicle intact as you zigzag through sun-soaked lands. Will you melt or prevail?",
    "url": "https://play.gamepix.com/gelatino/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/gelatino/cover/gelatino.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-65666",
    "providerId": "65666",
    "title": "Penalty Kick Wiz",
    "category": "Sports",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Sports",
    "description": "Step into the adrenaline-filled duel of Penalty Kick Wiz, where every shot and save is a crucial dance of precision and anticipation. Master the art of split-second decisions, outwit your opponent, and seize victory through strategic plays that test both your mental and physical reflexes.",
    "instructions": "Step into the adrenaline-filled duel of Penalty Kick Wiz, where every shot and save is a crucial dance of precision and anticipation. Master the art of split-second decisions, outwit your opponent, and seize victory through strategic plays that test both your mental and physical reflexes.",
    "url": "https://play.gamepix.com/penalty-kick-wiz/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/penalty-kick-wiz/cover/penalty-kick-wiz.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-11716W",
    "providerId": "11716W",
    "title": "Stickman Warriors",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Fighting",
    "description": "Unleash your inner stickman hero in Stickman Warriors, a thrilling fighting RPG. Ascend the ranks by mastering combat against powerful Saints. Maximize your strategy with daily rewards and diverse stickman attributes. Battle your way to the ultimate S rank and become the supreme stickman warrior!",
    "instructions": "Unleash your inner stickman hero in Stickman Warriors, a thrilling fighting RPG. Ascend the ranks by mastering combat against powerful Saints. Maximize your strategy with daily rewards and diverse stickman attributes. Battle your way to the ultimate S rank and become the supreme stickman warrior!",
    "url": "https://play.gamepix.com/stickman-warriors-1/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/stickman-warriors-1/cover/stickman-warriors-1.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-CICR7",
    "providerId": "CICR7",
    "title": "Merge Mine - Idle Clicker",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Adventure",
    "description": "Unleash your inner miner in Merge Mine - Idle Clicker. Tap into a diamond-rich vein, strategically upgrade tools, and merge them for enhanced mining power. Experience the thrill of turning hard work into shiny rewards, as you automate your mining empire and watch diamonds accumulate, even while you're away.",
    "instructions": "Unleash your inner miner in Merge Mine - Idle Clicker. Tap into a diamond-rich vein, strategically upgrade tools, and merge them for enhanced mining power. Experience the thrill of turning hard work into shiny rewards, as you automate your mining empire and watch diamonds accumulate, even while you're away.",
    "url": "https://play.gamepix.com/merge-mine-idle-clicker/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/merge-mine-idle-clicker/cover/merge-mine-idle-clicker.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-I29FM",
    "providerId": "I29FM",
    "title": "Flamit",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Adventure",
    "description": "Flamit puts your reflexes to the test in a swift race against a dwindling flame. Navigate 30 challenging, icy levels, lighting torches before time extinguishes your hopes. Strategize through snowy obstacles, evade icy enemies, and conquer two distinct game modes for an adrenaline-pumping experience.",
    "instructions": "Flamit puts your reflexes to the test in a swift race against a dwindling flame. Navigate 30 challenging, icy levels, lighting torches before time extinguishes your hopes. Strategize through snowy obstacles, evade icy enemies, and conquer two distinct game modes for an adrenaline-pumping experience.",
    "url": "https://play.gamepix.com/flamit/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/flamit/cover/flamit.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-T1A10",
    "providerId": "T1A10",
    "title": "Stickman Street Fighting 3D",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Fighting",
    "description": "Get ready to dominate the streets as a fearless stickman in Stickman Street Fighting 3D! This intense brawler challenges you to crush foes with strategic blows and quick reflexes. Break objects for unexpected power-ups, wield weapons for added punch, and prove you're the toughest stickman around.",
    "instructions": "Get ready to dominate the streets as a fearless stickman in Stickman Street Fighting 3D! This intense brawler challenges you to crush foes with strategic blows and quick reflexes. Break objects for unexpected power-ups, wield weapons for added punch, and prove you're the toughest stickman around.",
    "url": "https://play.gamepix.com/stickman-street-fighting/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/stickman-street-fighting/cover/stickman-street-fighting.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-R33T3",
    "providerId": "R33T3",
    "title": "Morphit",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Arcade",
    "description": "Morphit is an exhilarating arcade challenge where you must quickly morph your shape to overcome incoming obstacles. Engage your reflexes and precision in a vibrant, fast-paced environment, mastering the art of timing in a world that tests your adaptability at every turn. Stay alert, adapt, and survive the thrill!",
    "instructions": "Morphit is an exhilarating arcade challenge where you must quickly morph your shape to overcome incoming obstacles. Engage your reflexes and precision in a vibrant, fast-paced environment, mastering the art of timing in a world that tests your adaptability at every turn. Stay alert, adapt, and survive the thrill!",
    "url": "https://play.gamepix.com/morphit/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/morphit/cover/morphit.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-NBREF",
    "providerId": "NBREF",
    "title": "Robot Band - Find the differences",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Puzzle",
    "description": "Enter a whimsical world of musical robots in Robot Band - Find the Differences. Test your observation skills as you uncover subtle discrepancies in images. Progress through engaging levels with a keen eye and patience. Dive into this charming adventure where every discovery counts!",
    "instructions": "Enter a whimsical world of musical robots in Robot Band - Find the Differences. Test your observation skills as you uncover subtle discrepancies in images. Progress through engaging levels with a keen eye and patience. Dive into this charming adventure where every discovery counts!",
    "url": "https://play.gamepix.com/robot-band-find-the-differences/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/robot-band-find-the-differences/cover/robot-band-find-the-differences.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-VXGWI7",
    "providerId": "VXGWI7",
    "title": "Funny Shooter 2",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Shooter",
    "description": "Dive into the zany chaos of Funny Shooter 2, where every battle is a laugh-filled thrill ride. Face off against quirky enemies, upgrade your arsenal with endless customization options, and explore a whimsical world bursting with personality. This action-packed adventure is a hilariously unique gaming experience.",
    "instructions": "Dive into the zany chaos of Funny Shooter 2, where every battle is a laugh-filled thrill ride. Face off against quirky enemies, upgrade your arsenal with endless customization options, and explore a whimsical world bursting with personality. This action-packed adventure is a hilariously unique gaming experience.",
    "url": "https://play.gamepix.com/funny-shooter-2/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/funny-shooter-2/cover/funny-shooter-2.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-OK677",
    "providerId": "OK677",
    "title": "Sokoballs",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Ball",
    "description": "Sokoballs offers a delightful puzzle adventure where each level tests your strategic skills. Carefully maneuver balls onto switches using intuitive controls while enjoying vintage pixel art. As difficulty elevates, planning ahead becomes key to solving these increasingly challenging puzzles. Embrace the cerebral journey and relish the art of problem-solving.",
    "instructions": "Sokoballs offers a delightful puzzle adventure where each level tests your strategic skills. Carefully maneuver balls onto switches using intuitive controls while enjoying vintage pixel art. As difficulty elevates, planning ahead becomes key to solving these increasingly challenging puzzles. Embrace the cerebral journey and relish the art of problem-solving.",
    "url": "https://play.gamepix.com/sokoballs/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/sokoballs/cover/sokoballs.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-323G7",
    "providerId": "323G7",
    "title": "Going Right",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Animal",
    "description": "Embark on a thrilling aerial journey as you guide a determined bird back to its nest in \"Going Right.\" Navigate through dynamic obstacles using intuitive one-touch controls. Embrace the challenge across multiple modes, collect coins for customization, and strategize your taps to master this addictive arcade adventure.",
    "instructions": "Embark on a thrilling aerial journey as you guide a determined bird back to its nest in \"Going Right.\" Navigate through dynamic obstacles using intuitive one-touch controls. Embrace the challenge across multiple modes, collect coins for customization, and strategize your taps to master this addictive arcade adventure.",
    "url": "https://play.gamepix.com/going-right/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/going-right/cover/going-right.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-P0721",
    "providerId": "P0721",
    "title": "Canjump",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Fun",
    "description": "Leap into a thrilling arcade adventure with Canjump! Master the art of well-timed jumps as a monster navigating perilous terrains. With only one button to control, sharpen your reflexes to conquer increasingly tough obstacles and enemies, all while aiming for the highest score in this endlessly entertaining challenge.",
    "instructions": "Leap into a thrilling arcade adventure with Canjump! Master the art of well-timed jumps as a monster navigating perilous terrains. With only one button to control, sharpen your reflexes to conquer increasingly tough obstacles and enemies, all while aiming for the highest score in this endlessly entertaining challenge.",
    "url": "https://play.gamepix.com/canjump/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/canjump/cover/canjump.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-7MS9M",
    "providerId": "7MS9M",
    "title": "Moto X3M: Spooky Land",
    "category": "Racing",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Racing",
    "description": "Dive into the eerie thrills of Moto X3M: Spooky Land, where every turn is a challenge against the supernatural. Master gravity-defying stunts on spooky tracks, dodge bone-rattling obstacles, and ride like the wind to unlock creepy new gear. Can you handle the haunting speed and survive the ghoulish adventure?",
    "instructions": "Dive into the eerie thrills of Moto X3M: Spooky Land, where every turn is a challenge against the supernatural. Master gravity-defying stunts on spooky tracks, dodge bone-rattling obstacles, and ride like the wind to unlock creepy new gear. Can you handle the haunting speed and survive the ghoulish adventure?",
    "url": "https://play.gamepix.com/moto-x3m-spooky-land/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/moto-x3m-spooky-land/cover/moto-x3m-spooky-land.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-GS7CA",
    "providerId": "GS7CA",
    "title": "Slope Racing 3D",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Ball",
    "description": "Experience exhilarating speed as you guide a relentless ball down a vibrant, ever-changing slope. Navigate through dynamic obstacles, hit boost pads, and gather gems while skillfully using power-ups. With endless ramps and increasing challenges, Slope Racing 3D offers a fast-paced thrill ride testing your reflexes and precision.",
    "instructions": "Experience exhilarating speed as you guide a relentless ball down a vibrant, ever-changing slope. Navigate through dynamic obstacles, hit boost pads, and gather gems while skillfully using power-ups. With endless ramps and increasing challenges, Slope Racing 3D offers a fast-paced thrill ride testing your reflexes and precision.",
    "url": "https://play.gamepix.com/slope-racing-3d/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/slope-racing-3d/cover/slope-racing-3d.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-NN525H",
    "providerId": "NN525H",
    "title": "Knockback Knights",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Fighting",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/knockback-knights/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/knockback-knights/cover/knockback-knights.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-A58PA",
    "providerId": "A58PA",
    "title": "Royal Couple Halloween Party",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Games For Girls",
    "description": "Step into a whimsical world where creating enchanting Halloween outfits for royal couples is your mission. With vibrant graphics and easy point-and-click controls, mix and match wardrobes to craft unique, thematic ensembles. Unleash your creativity as you turn the festive night into a magical masterpiece.",
    "instructions": "Step into a whimsical world where creating enchanting Halloween outfits for royal couples is your mission. With vibrant graphics and easy point-and-click controls, mix and match wardrobes to craft unique, thematic ensembles. Unleash your creativity as you turn the festive night into a magical masterpiece.",
    "url": "https://play.gamepix.com/royal-couple-halloween-party/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/royal-couple-halloween-party/cover/royal-couple-halloween-party.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-222C33",
    "providerId": "222C33",
    "title": "Epic Duck",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Arcade",
    "description": "Embark on an adventurous journey with Epic Duck, where clever exploration and precise timing lead to success. Navigate charming levels, uncover hidden keys, and unlock doorways to progress, all while honing your puzzle-solving skills. With engaging challenges and delightful visuals, it's a delightful test of strategy and reflexes.",
    "instructions": "Embark on an adventurous journey with Epic Duck, where clever exploration and precise timing lead to success. Navigate charming levels, uncover hidden keys, and unlock doorways to progress, all while honing your puzzle-solving skills. With engaging challenges and delightful visuals, it's a delightful test of strategy and reflexes.",
    "url": "https://play.gamepix.com/epic-duck/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/epic-duck/cover/epic-duck.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-OR4NC4",
    "providerId": "OR4NC4",
    "title": "Commando Force 2",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "First Person Shooter",
    "description": "Dive into high-octane action with Commando Force 2! Engage in thrilling team battles or go head-to-head in free-for-alls. Unlock rewards through the Battle Pass while mastering diverse maps and weaponry. With smooth controls, stunning graphics, and strategic gameplay, it's a shooter experience that's easy to start, challenging to master.",
    "instructions": "Dive into high-octane action with Commando Force 2! Engage in thrilling team battles or go head-to-head in free-for-alls. Unlock rewards through the Battle Pass while mastering diverse maps and weaponry. With smooth controls, stunning graphics, and strategic gameplay, it's a shooter experience that's easy to start, challenging to master.",
    "url": "https://play.gamepix.com/commando-force-2/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/commando-force-2/cover/commando-force-2.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-76AL1S",
    "providerId": "76AL1S",
    "title": "Impossible Repair Shop",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Brain",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/impossible-repair-shop/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/impossible-repair-shop/cover/impossible-repair-shop.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-NO71E",
    "providerId": "NO71E",
    "title": "Injection Invasion",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Arcade",
    "description": "Dodge and weave in Injection Invasion, an exciting platformer where quick reflexes and strategy are essential. Guide a boy through a perilous world filled with incoming injections, using precision and timing to survive. Master the art of evasive maneuvers and see how long you can last!",
    "instructions": "Dodge and weave in Injection Invasion, an exciting platformer where quick reflexes and strategy are essential. Guide a boy through a perilous world filled with incoming injections, using precision and timing to survive. Master the art of evasive maneuvers and see how long you can last!",
    "url": "https://play.gamepix.com/injection-invasion/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/injection-invasion/cover/injection-invasion.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-FZBGMS",
    "providerId": "FZBGMS",
    "title": "Santabalt",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Christmas",
    "description": "Dive into the festive spirit with Santabalt, an exhilarating endless runner with Santa at the helm. Leap between rooftops, dodging obstacles at thrilling speed with just a tap or click. Hone your timing and reflexes, extending Santa's journey in this addictive holiday adventure loaded with jolly excitement.",
    "instructions": "Dive into the festive spirit with Santabalt, an exhilarating endless runner with Santa at the helm. Leap between rooftops, dodging obstacles at thrilling speed with just a tap or click. Hone your timing and reflexes, extending Santa's journey in this addictive holiday adventure loaded with jolly excitement.",
    "url": "https://play.gamepix.com/santabalt/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/santabalt/cover/santabalt.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-4HOY7G",
    "providerId": "4HOY7G",
    "title": "The Floor Is Lying",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Platformer",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/the-floor-is-lying/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/the-floor-is-lying/cover/the-floor-is-lying.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-98373R",
    "providerId": "98373R",
    "title": "Gravity Merge",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Puzzle",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/gravity-merge/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/gravity-merge/cover/gravity-merge.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-57VI5P",
    "providerId": "57VI5P",
    "title": "Evo Pit",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Io",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/evo-pit/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/evo-pit/cover/evo-pit.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-S1HEA",
    "providerId": "S1HEA",
    "title": "Car Crash Test",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Arcade",
    "description": "Unleash chaos in Car Crash Test, where the thrill of spectacular automotive destruction meets real-time physics and stunning 3D graphics. Earn coins through strategic demolition, unlock new cars, and explore challenging tracks. Master time dilation and unleash explosive wrecks in this endlessly enticing and adrenaline-pumping experience.",
    "instructions": "Unleash chaos in Car Crash Test, where the thrill of spectacular automotive destruction meets real-time physics and stunning 3D graphics. Earn coins through strategic demolition, unlock new cars, and explore challenging tracks. Master time dilation and unleash explosive wrecks in this endlessly enticing and adrenaline-pumping experience.",
    "url": "https://play.gamepix.com/car-crash-test/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/car-crash-test/cover/car-crash-test.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-748S4",
    "providerId": "748S4",
    "title": "Endless Car Chase",
    "category": "Racing",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Racing",
    "description": "Dive into the exhilarating chaos of Endless Car Chase, where evading the relentless police becomes a thrilling art. Customize your ride, collect power-ups, and master sharp maneuvers as you navigate through hectic streets. With every heart-pounding chase, design your unique escape experience while pursuing the ultimate high score.",
    "instructions": "Dive into the exhilarating chaos of Endless Car Chase, where evading the relentless police becomes a thrilling art. Customize your ride, collect power-ups, and master sharp maneuvers as you navigate through hectic streets. With every heart-pounding chase, design your unique escape experience while pursuing the ultimate high score.",
    "url": "https://play.gamepix.com/endless-car-chase/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/endless-car-chase/cover/endless-car-chase.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-55D0D1",
    "providerId": "55D0D1",
    "title": "Hoop World",
    "category": "Sports",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Basketball",
    "description": "In Hoop World, become a master of aerial acrobatics with precision mouse clicks. Soar through the air, nail flipping dunks, and outshine with style. Simple controls meet spectacular moves, making each perfect dunk a thrilling achievement in this dynamic 3D basketball experience.",
    "instructions": "In Hoop World, become a master of aerial acrobatics with precision mouse clicks. Soar through the air, nail flipping dunks, and outshine with style. Simple controls meet spectacular moves, making each perfect dunk a thrilling achievement in this dynamic 3D basketball experience.",
    "url": "https://play.gamepix.com/hoop-world/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/hoop-world/cover/hoop-world.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-4AIAL1",
    "providerId": "4AIAL1",
    "title": "Val d'Agri Race",
    "category": "Racing",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Car",
    "description": "Race through lively Viggiano streets, dodging traffic and escaping patrols in Val d' Agri Race. Collect coins to unlock and customize flashy cars, harness temporary powers, and cause thrilling destruction to access exclusive rides. Experience heart-pounding action in every high-speed chase.",
    "instructions": "Race through lively Viggiano streets, dodging traffic and escaping patrols in Val d' Agri Race. Collect coins to unlock and customize flashy cars, harness temporary powers, and cause thrilling destruction to access exclusive rides. Experience heart-pounding action in every high-speed chase.",
    "url": "https://play.gamepix.com/val-d-agri-race/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/val-d-agri-race/cover/val-d-agri-race.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-AAMJR",
    "providerId": "AAMJR",
    "title": "Run & Jump Jumbo Runner",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Arcade",
    "description": "Race through dynamic terrains in Run & Jump Jumbo Runner, where precision and timing are your allies. As you fly and dodge obstacles, each quick tap unlocks faster speeds and thrilling challenges. Master the exhilarating arcade action and discover the addictive thrills of gravity-defying runs and flights.",
    "instructions": "Race through dynamic terrains in Run & Jump Jumbo Runner, where precision and timing are your allies. As you fly and dodge obstacles, each quick tap unlocks faster speeds and thrilling challenges. Master the exhilarating arcade action and discover the addictive thrills of gravity-defying runs and flights.",
    "url": "https://play.gamepix.com/ran-and-jump-jambo-runner/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/ran-and-jump-jambo-runner/cover/ran-and-jump-jambo-runner.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-40264",
    "providerId": "40264",
    "title": "TenTrix",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Block",
    "description": "Unleash your strategic prowess in TenTrix, a compelling blend of simplicity and creativity. Effortlessly arrange falling blocks on a 10x10 grid to clear lines and score points. With unrotatable shapes and endless possibilities, it's a fresh twist on classic Tetris, offering endless fun on both PC and mobile.",
    "instructions": "Unleash your strategic prowess in TenTrix, a compelling blend of simplicity and creativity. Effortlessly arrange falling blocks on a 10x10 grid to clear lines and score points. With unrotatable shapes and endless possibilities, it's a fresh twist on classic Tetris, offering endless fun on both PC and mobile.",
    "url": "https://play.gamepix.com/tentrix/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/tentrix/cover/tentrix.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-GOR11V",
    "providerId": "GOR11V",
    "title": "Everything Forge",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Puzzle",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/everything-forge/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/everything-forge/cover/everything-forge.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-S1L1AO",
    "providerId": "S1L1AO",
    "title": "Lotl Spa",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Clicker",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/lotl-spa/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/lotl-spa/cover/lotl-spa.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-R11CK",
    "providerId": "R11CK",
    "title": "Strike Galaxy Attack",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Arcade",
    "description": "Take command of a lone, powerful spaceship in Strike Galaxy Attack. Dodge and weave through endless waves of colorful space birds while unleashing streams of gunfire. Collect upgrades to enhance your ship and outmaneuver enemies as you aim to dominate the galaxy in this thrilling 2D arcade shooter.",
    "instructions": "Take command of a lone, powerful spaceship in Strike Galaxy Attack. Dodge and weave through endless waves of colorful space birds while unleashing streams of gunfire. Collect upgrades to enhance your ship and outmaneuver enemies as you aim to dominate the galaxy in this thrilling 2D arcade shooter.",
    "url": "https://play.gamepix.com/strike-galaxy-attack/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/strike-galaxy-attack/cover/strike-galaxy-attack.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-T0OO6",
    "providerId": "T0OO6",
    "title": "Dotto Botto",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Retro",
    "description": "Embark on an epic adventure with pixel hero Dotto Botto in this charming retro platformer. Facing hazardous spikes and deadly enemies across diverse levels, you'll jump and dodge with precision. Find power-ups, solve challenges, and prepare for a climactic showdown against a colossal final boss! Will you guide Dotto home?",
    "instructions": "Embark on an epic adventure with pixel hero Dotto Botto in this charming retro platformer. Facing hazardous spikes and deadly enemies across diverse levels, you'll jump and dodge with precision. Find power-ups, solve challenges, and prepare for a climactic showdown against a colossal final boss! Will you guide Dotto home?",
    "url": "https://play.gamepix.com/dotto-botto/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/dotto-botto/cover/dotto-botto.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-6OIGN",
    "providerId": "6OIGN",
    "title": "Bouncing Egg",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Arcade",
    "description": "Guide a fragile egg through a vibrant pixel-art world, bouncing on rotating circles to smash menacing faces. With its simple tap controls and addictive gameplay, every moment demands precision, patience, and perfect timing. Can you master the escalating challenge and keep your egg intact?",
    "instructions": "Guide a fragile egg through a vibrant pixel-art world, bouncing on rotating circles to smash menacing faces. With its simple tap controls and addictive gameplay, every moment demands precision, patience, and perfect timing. Can you master the escalating challenge and keep your egg intact?",
    "url": "https://play.gamepix.com/bouncing-egg/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/bouncing-egg/cover/bouncing-egg.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-S17B2S",
    "providerId": "S17B2S",
    "title": "Merge Battle Tactics",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Fighting",
    "description": "Summon and merge creatures in a captivating fantasy realm where strategy is your ally. Engage in thrilling battles by combining monsters to create powerful warriors, balance your forces on the battlefield, and earn coins to expand your ranks. Will your tactical prowess lead you to victory?",
    "instructions": "Summon and merge creatures in a captivating fantasy realm where strategy is your ally. Engage in thrilling battles by combining monsters to create powerful warriors, balance your forces on the battlefield, and earn coins to expand your ranks. Will your tactical prowess lead you to victory?",
    "url": "https://play.gamepix.com/merge-battle-tactics/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/merge-battle-tactics/cover/merge-battle-tactics.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-87881",
    "providerId": "87881",
    "title": "Evil Invader",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Arcade",
    "description": "Evil Invader plunges you into a dystopian battlefield overrun by monstrous foes. Engage in heart-pounding, fast-paced shooting action as you fight relentless enemies with an arsenal of weapons. Strategize with power-ups, master enemy patterns, and level up to unlock devastating firepower in this intense survival challenge.",
    "instructions": "Evil Invader plunges you into a dystopian battlefield overrun by monstrous foes. Engage in heart-pounding, fast-paced shooting action as you fight relentless enemies with an arsenal of weapons. Strategize with power-ups, master enemy patterns, and level up to unlock devastating firepower in this intense survival challenge.",
    "url": "https://play.gamepix.com/evil-invader/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/evil-invader/cover/evil-invader.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-N8328",
    "providerId": "N8328",
    "title": "War of Tanks 3D",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Adventure",
    "description": "Command your tank in intense battles where strategy and precision are key. Navigate dynamic terrains, meticulously aim your cannons, and tactically outmaneuver your foes. Fast-paced action awaits as you strive to dominate the battlefield, mastering your tank\u2019s firepower while leveraging the environment for ultimate victory.",
    "instructions": "Command your tank in intense battles where strategy and precision are key. Navigate dynamic terrains, meticulously aim your cannons, and tactically outmaneuver your foes. Fast-paced action awaits as you strive to dominate the battlefield, mastering your tank\u2019s firepower while leveraging the environment for ultimate victory.",
    "url": "https://play.gamepix.com/war-of-tanks-3d/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/war-of-tanks-3d/cover/war-of-tanks-3d.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-LUU58C",
    "providerId": "LUU58C",
    "title": "Cauldron Counter",
    "category": "Strategy",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Simulation",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/cauldron-counter/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/cauldron-counter/cover/cauldron-counter.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-NELEII",
    "providerId": "NELEII",
    "title": "Demolition Derby Life",
    "category": "Racing",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Racing",
    "description": "Plunge into the chaotic thrill of Demolition Derby Life, a high-octane derby simulator. Strategically smash your way to victory, upgrading your car while trying to outlast the competition. Experience the adrenaline rush of tactical destruction and exhilarating impacts in this immersive single-player experience. Can you survive the arena?",
    "instructions": "Plunge into the chaotic thrill of Demolition Derby Life, a high-octane derby simulator. Strategically smash your way to victory, upgrading your car while trying to outlast the competition. Experience the adrenaline rush of tactical destruction and exhilarating impacts in this immersive single-player experience. Can you survive the arena?",
    "url": "https://play.gamepix.com/demolition-derby-life/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/demolition-derby-life/cover/demolition-derby-life.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-3A434",
    "providerId": "3A434",
    "title": "Yummy Toast",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Games For Girls",
    "description": "In Yummy Toast, become the toast crafting expert in a lively kitchen setting. Quickly serve up delightful creations using a variety of ingredients to satisfy customer orders. Speed and precision are your allies as you unlock challenging levels and strive to become the ultimate toast maestro.",
    "instructions": "In Yummy Toast, become the toast crafting expert in a lively kitchen setting. Quickly serve up delightful creations using a variety of ingredients to satisfy customer orders. Speed and precision are your allies as you unlock challenging levels and strive to become the ultimate toast maestro.",
    "url": "https://play.gamepix.com/yummy-toast/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/yummy-toast/cover/yummy-toast.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-ID19L1",
    "providerId": "ID19L1",
    "title": "Idle Craft 3D",
    "category": "Strategy",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Idle",
    "description": " Rebuild your home in Idle Craft 3D where you recruit workers and summon elders to manage fatigue. Enjoy a vibrant 3D world and continuous progress, even when idle. Strategize wisely to enhance your workforce, master resource balance, and marvel at the satisfying transformation around you.",
    "instructions": " Rebuild your home in Idle Craft 3D where you recruit workers and summon elders to manage fatigue. Enjoy a vibrant 3D world and continuous progress, even when idle. Strategize wisely to enhance your workforce, master resource balance, and marvel at the satisfying transformation around you.",
    "url": "https://play.gamepix.com/idle-craft-3d-1/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/idle-craft-3d-1/cover/idle-craft-3d-1.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-RR578",
    "providerId": "RR578",
    "title": "Perimeter - Legate Edition",
    "category": "Strategy",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Strategy",
    "description": "Command the Exodus civilization in a groundbreaking RTS where strategic terraforming reshapes battlefields. Build defensive perimeters and seize territories in a dynamic, evolving environment. Adapt, survive, and lead your people to victory in a world where earth's future rests in your hands.",
    "instructions": "Command the Exodus civilization in a groundbreaking RTS where strategic terraforming reshapes battlefields. Build defensive perimeters and seize territories in a dynamic, evolving environment. Adapt, survive, and lead your people to victory in a world where earth's future rests in your hands.",
    "url": "https://play.gamepix.com/perimeter/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/perimeter/cover/perimeter.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-3E79E",
    "providerId": "3E79E",
    "title": "Robo-Butcher",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Robots",
    "description": "Engage in relentless 2D platform-arena battles as a humanoid robot, striving for supremacy. Outmaneuver and obliterate waves of robotic adversaries with tactical agility. Upgrade your arsenal, seize power-ups from crates, and strategically exploit enemy weaknesses for a thrilling test of endurance and skill.",
    "instructions": "Engage in relentless 2D platform-arena battles as a humanoid robot, striving for supremacy. Outmaneuver and obliterate waves of robotic adversaries with tactical agility. Upgrade your arsenal, seize power-ups from crates, and strategically exploit enemy weaknesses for a thrilling test of endurance and skill.",
    "url": "https://play.gamepix.com/robo-butcher/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/robo-butcher/cover/robo-butcher.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-I3PTAN",
    "providerId": "I3PTAN",
    "title": "Spinning Oia Oia Cat Bricker",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Block",
    "description": "Join the energetic Oia Oia cat in a vivid brick-breaking adventure where vibrant visuals and lively meows propel you forward. Master your aim, shatter bricks with precision, and groove through each escalating level, all while soaking up the dynamic, cheering atmosphere for an endlessly fun experience.",
    "instructions": "Join the energetic Oia Oia cat in a vivid brick-breaking adventure where vibrant visuals and lively meows propel you forward. Master your aim, shatter bricks with precision, and groove through each escalating level, all while soaking up the dynamic, cheering atmosphere for an endlessly fun experience.",
    "url": "https://play.gamepix.com/spinning-oia-oia-cat-bricker/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/spinning-oia-oia-cat-bricker/cover/spinning-oia-oia-cat-bricker.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-R5R16",
    "providerId": "R5R16",
    "title": "Face Breaker",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Ball",
    "description": "Face Breaker challenges your reflexes in a dynamic arcade puzzle setting. Control a paddle to keep a quirky square-face-ball in play, crushing blocks through 45 escalating levels. With each bounce, the speed surges, testing your timing and strategy in this riveting race against the clock!",
    "instructions": "Face Breaker challenges your reflexes in a dynamic arcade puzzle setting. Control a paddle to keep a quirky square-face-ball in play, crushing blocks through 45 escalating levels. With each bounce, the speed surges, testing your timing and strategy in this riveting race against the clock!",
    "url": "https://play.gamepix.com/face-breaker/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/face-breaker/cover/face-breaker.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-48IRDO",
    "providerId": "48IRDO",
    "title": "Drill to the Core",
    "category": "Strategy",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Idle",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/drill-to-the-core/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/drill-to-the-core/cover/drill-to-the-core.png?w=320",
    "orientation": "all",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-M20778",
    "providerId": "M20778",
    "title": "Emberdeck",
    "category": "Classic",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Card",
    "description": "",
    "instructions": "Follow the instructions inside the game. Use the game\u2019s own controls and menus to begin.",
    "url": "https://play.gamepix.com/emberdeck/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/emberdeck/cover/emberdeck.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-71BTT",
    "providerId": "71BTT",
    "title": "BattleBox",
    "category": "Classic",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Board",
    "description": "Unearth hidden treasures while sidestepping treacherous monsters in BattleBox, a thrilling puzzle adventure that will challenge your memory and wits. Strategize and recall the secret grid layout, aiming for riches while avoiding peril. Survive by maintaining your health with handy strawberries, ensuring every play is an exciting discovery.",
    "instructions": "Unearth hidden treasures while sidestepping treacherous monsters in BattleBox, a thrilling puzzle adventure that will challenge your memory and wits. Strategize and recall the secret grid layout, aiming for riches while avoiding peril. Survive by maintaining your health with handy strawberries, ensuring every play is an exciting discovery.",
    "url": "https://play.gamepix.com/battlebox/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/battlebox/cover/battlebox.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-C4LMG",
    "providerId": "C4LMG",
    "title": "Ultimate Flying Car",
    "category": "Sports",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Sports",
    "description": "Race at breakneck speeds and soar through the skies in Ultimate Flying Car. Merge reality with fantasy as you navigate urban landscapes in sleek, aerodynamic vehicles. Challenge friends in thrilling multiplayer races, and explore expansive environments in style with daring stunts and strategic use of power boosts.",
    "instructions": "Race at breakneck speeds and soar through the skies in Ultimate Flying Car. Merge reality with fantasy as you navigate urban landscapes in sleek, aerodynamic vehicles. Challenge friends in thrilling multiplayer races, and explore expansive environments in style with daring stunts and strategic use of power boosts.",
    "url": "https://play.gamepix.com/ultimate-flying-car/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/ultimate-flying-car/cover/ultimate-flying-car.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-UURR7U",
    "providerId": "UURR7U",
    "title": "Spider Evolution Runner Game",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Runner",
    "description": "Embark on a thrilling journey as a spider in this dynamic 3D runner. Consume insects and smaller spiders to grow larger, navigate challenging terrains, and dodge threats. Explore vibrant landscapes as you strategize your survival and aim to become the realm's biggest spider. Ready for a bite-sized adventure?",
    "instructions": "Embark on a thrilling journey as a spider in this dynamic 3D runner. Consume insects and smaller spiders to grow larger, navigate challenging terrains, and dodge threats. Explore vibrant landscapes as you strategize your survival and aim to become the realm's biggest spider. Ready for a bite-sized adventure?",
    "url": "https://play.gamepix.com/spider-evolution-runner-game/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/spider-evolution-runner-game/cover/spider-evolution-runner-game.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-6CTE0",
    "providerId": "6CTE0",
    "title": "Match Mystery",
    "category": "Puzzle",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Match 3",
    "description": "Immerse yourself in Match Mystery, a match-3 puzzle adventure with endless challenges and a captivating storyline. Dive into stunning visuals, where each strategic move unravels new plots. With infinite levels and increasing difficulty, it's a delightful test of your puzzle-solving skills. Perfect for all ages seeking brain-teasing fun.",
    "instructions": "Immerse yourself in Match Mystery, a match-3 puzzle adventure with endless challenges and a captivating storyline. Dive into stunning visuals, where each strategic move unravels new plots. With infinite levels and increasing difficulty, it's a delightful test of your puzzle-solving skills. Perfect for all ages seeking brain-teasing fun.",
    "url": "https://play.gamepix.com/match-mystery/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/match-mystery/cover/match-mystery.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  },
  {
    "id": "gpx-B4BB4",
    "providerId": "B4BB4",
    "title": "Boing Bang",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Retro",
    "description": "Boing Bang tosses you into frenetic action as you control a quirky creature armed with a blaster. Navigate through bouncing chaos, shatter massive balls into pieces, and use platforms strategically. With unpredictable bouncing patterns to master and survival at stake, every shot counts in this thrilling arcade adventure.",
    "instructions": "Boing Bang tosses you into frenetic action as you control a quirky creature armed with a blaster. Navigate through bouncing chaos, shatter massive balls into pieces, and use platforms strategically. With unpredictable bouncing patterns to master and survival at stake, every shot counts in this thrilling arcade adventure.",
    "url": "https://play.gamepix.com/boing-bang/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/boing-bang/cover/boing-bang.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-20XI2",
    "providerId": "20XI2",
    "title": "Drunken Boxing 2",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Fighting",
    "description": "Step into chaos with Drunken Boxing 2, where intoxicated stickmen clash in strategic bouts of reflex and endurance. With glistening 3D visuals, vibrant animations, and adrenaline-pumping action, battle solo or with friends for a uniquely boozy arcade experience where energy management is the key to victory.",
    "instructions": "Step into chaos with Drunken Boxing 2, where intoxicated stickmen clash in strategic bouts of reflex and endurance. With glistening 3D visuals, vibrant animations, and adrenaline-pumping action, battle solo or with friends for a uniquely boozy arcade experience where energy management is the key to victory.",
    "url": "https://play.gamepix.com/drunken-boxing-2/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/drunken-boxing-2/cover/drunken-boxing-2.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-42ZZO",
    "providerId": "42ZZO",
    "title": "Worms Zone",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Snake",
    "description": "Worms Zone combines the classic Snake experience with vibrant twists, where worms devour their way to gigantism. Navigate through colorful zones, grow faster, and customize your worm. Balance speed and strategy to avoid rivals, collect power-ups, and emerge as the longest worm. Slither, compete, and claim worm supremacy!",
    "instructions": "Worms Zone combines the classic Snake experience with vibrant twists, where worms devour their way to gigantism. Navigate through colorful zones, grow faster, and customize your worm. Balance speed and strategy to avoid rivals, collect power-ups, and emerge as the longest worm. Slither, compete, and claim worm supremacy!",
    "url": "https://play.gamepix.com/worms-zone/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/worms-zone/cover/worms-zone.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-1637O6",
    "providerId": "1637O6",
    "title": "Golf Orbit",
    "category": "Sports",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Golf",
    "description": "Unleash your inner golfer with Golf Orbit, a dynamic twist on traditional golf. Master the power meter to blast balls through zany courses, overcoming quirky obstacles. Customize your golfer, earn rewards, and test your strength as you aim for the green, all with a light-hearted, entertaining spin.",
    "instructions": "Unleash your inner golfer with Golf Orbit, a dynamic twist on traditional golf. Master the power meter to blast balls through zany courses, overcoming quirky obstacles. Customize your golfer, earn rewards, and test your strength as you aim for the green, all with a light-hearted, entertaining spin.",
    "url": "https://play.gamepix.com/golf-orbit/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/golf-orbit/cover/golf-orbit.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-EOKLL8",
    "providerId": "EOKLL8",
    "title": "Super Billy Boy",
    "category": "Arcade",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Platformer",
    "description": "Embark on a thrilling journey with Super Billy Boy as you navigate a pixelated world filled with traps and alien foes. Rescue your friend by mastering platformer challenges that demand precision and clever strategies. Dive into this nostalgic adventure where each level brings new excitement and unexpected twists.",
    "instructions": "Embark on a thrilling journey with Super Billy Boy as you navigate a pixelated world filled with traps and alien foes. Rescue your friend by mastering platformer challenges that demand precision and clever strategies. Dive into this nostalgic adventure where each level brings new excitement and unexpected twists.",
    "url": "https://play.gamepix.com/super-billy-boy/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/super-billy-boy/cover/super-billy-boy.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-222OE1",
    "providerId": "222OE1",
    "title": "The Room",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Shooter",
    "description": "The Room immerses you in intense, nostalgic 2D shooter action as you defend your domain's heart against relentless enemy waves. Precision, strategy, and quick reflexes are key. With intuitive controls and a charming pixel art style, each escalating challenge delivers adrenaline-fueled excitement and addictive gameplay.",
    "instructions": "The Room immerses you in intense, nostalgic 2D shooter action as you defend your domain's heart against relentless enemy waves. Precision, strategy, and quick reflexes are key. With intuitive controls and a charming pixel art style, each escalating challenge delivers adrenaline-fueled excitement and addictive gameplay.",
    "url": "https://play.gamepix.com/the-room/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/the-room/cover/the-room.png?w=320",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gpx-40434",
    "providerId": "40434",
    "title": "Magikmon",
    "category": "Action",
    "engine": "gamepix",
    "provider": "GamePix",
    "art": 0,
    "tag": "GAMEPIX",
    "meta": "Monster",
    "description": "Embark on a fantastical journey in Magikmon, where you capture and train quirky creatures to build your ultimate monster team. Engage in thrilling battles, exploring a magical world brimming with adventure and surprises. Immerse yourself in this delightful RPG experience and discover the joy of strategy and exploration.",
    "instructions": "Embark on a fantastical journey in Magikmon, where you capture and train quirky creatures to build your ultimate monster team. Engage in thrilling battles, exploring a magical world brimming with adventure and surprises. Immerse yourself in this delightful RPG experience and discover the joy of strategy and exploration.",
    "url": "https://play.gamepix.com/magikmon/embed?sid=5005N",
    "thumbnail": "https://img.gamepix.com/games/magikmon/cover/magikmon.png?w=320",
    "orientation": "portrait",
    "width": 600,
    "height": 800
  }
];
