/* GameMonetize catalog snapshot; original provider URLs preserved. */
window.GAMEMONETIZE_CATALOG = [
  {
    "id": "gm-86779",
    "providerId": "86779",
    "title": "Steel Directive: City Zero",
    "category": "Action",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Shooting 1 Player, 2D, Action, Robot, Shooting",
    "description": "Take back City Zero as an armored enforcer in this 2D action shooter. Fight human gangs, confront increasingly dangerous robots, and defeat powerful bosses across 20 distinct missions. Rescue civilians, collect evidence, disable security systems, and reach extraction using tactical cover, multiple weapons, grenades, and shields. Web Dev https://www.insanegamesonline.com/",
    "instructions": "A D or Left Right move Space jump Mouse click or J shoot S C kneel E interact or take weapon V scan Q switch weapon R reload Shift dodge G grenade F shield P pause Mobile use the on-screen buttons",
    "url": "https://html5.gamemonetize.co/2htlt0jzz98u493u3z9jt9wsykiqtv0a/",
    "thumbnail": "https://img.gamemonetize.com/2htlt0jzz98u493u3z9jt9wsykiqtv0a/512x384.jpg",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gm-86803",
    "providerId": "86803",
    "title": "Black Hole Swallow Master",
    "category": "Puzzle",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Puzzle 2026 games, Adventure, Best Games, Casual",
    "description": "Black Hole Swallow Master is an exciting and addictive casual arcade game where you control a powerful black hole and swallow everything in your path. Move around the environment, collect objects, grow bigger, and challenge yourself to consume as much as possible before time runs out. Start small and carefully move your black hole across the level to swallow objects and increase your size. As your black hole game adventure continues, you can consume larger objects and clear more of the environment. Plan your movement, find the best targets, and become the ultimate swallowing master.",
    "instructions": "- To click any button use mouse",
    "url": "https://html5.gamemonetize.co/spagtaqty5vokjah2z0gcuytvz8ticym/",
    "thumbnail": "https://img.gamemonetize.com/spagtaqty5vokjah2z0gcuytvz8ticym/512x384.jpg",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gm-86633",
    "providerId": "86633",
    "title": "Online KitPvP : 50vs50",
    "category": "Action",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Multiplayer 1 Player, 2026 games, 3D, 3D Games, Arena, mineblock, Minecraft, PvP",
    "description": "Join exciting battles against real players in Online Kit PvP! Enter the arena, choose the kit that suits you, and fight against your opponents. Use different equipment and abilities to define your playstyle, move quickly, and work together with your teammates to defeat the opposing team. Strategy, reflexes, and choosing the right equipment will be the keys to victory. Survive the arena, defeat your opponents, and lead your team to victory. Join the Online Kit PvP battle and show your skills!",
    "instructions": "Use the WASD keys to move press Space to jump and use the left mouse button to attack Mobile controls are also available",
    "url": "https://html5.gamemonetize.co/2ipfjlhx61qegnkn7ldkh2gig46ytn1z/",
    "thumbnail": "https://img.gamemonetize.com/2ipfjlhx61qegnkn7ldkh2gig46ytn1z/512x384.jpg",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gm-86428",
    "providerId": "86428",
    "title": "Twist and Tug",
    "category": "Puzzle",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Puzzle Brain, Casual, Fun, Logic",
    "description": "**Twist and Tug** is a creative rope puzzle game where you drag, connect, and arrange ropes to match the target shape. Position each node carefully, prevent ropes from overlapping, and recreate the correct pattern to complete each level. Puzzles become more complex as you progress, testing your logic, observation, and problem-solving skills. Master every rope challenge and enjoy satisfying brain-teasing gameplay!",
    "instructions": "Use mouse to play",
    "url": "https://html5.gamemonetize.co/kexlo2sm796v7rd06e3j39dkj2lz3bkd/",
    "thumbnail": "https://img.gamemonetize.com/kexlo2sm796v7rd06e3j39dkj2lz3bkd/512x384.jpg",
    "orientation": "landscape",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "gm-85719",
    "providerId": "85719",
    "title": "Stacky Hero Master Game",
    "category": "Puzzle",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Puzzle 2026 games, amazing, Best Games, Casual, Fun",
    "description": "Welcome to Stacky Hero Master Games: Bridge Runner Games, which is a fun and exciting maze puzzle game that challenges your brain while giving you hours of entertainment. Move through colorful mazes, collect blocks, build tall stacks, and find the correct path to reach the finish line. Every level brings a new puzzle, making the game more exciting as you progress. If you enjoy maze games, puzzle games, brain games, stack games, block collecting games, and casual offline games, then stacky maze is the perfect choice for you. Easy controls, smooth gameplay, and colorful graphics make this game enjoyable for players of all ages.",
    "instructions": "- To click any button use mouse",
    "url": "https://html5.gamemonetize.co/9q88up7l4oitsteo10kd09cou3g5bdy9/",
    "thumbnail": "https://img.gamemonetize.com/9q88up7l4oitsteo10kd09cou3g5bdy9/512x384.jpg",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gm-83277",
    "providerId": "83277",
    "title": "Rope Push Game",
    "category": "Puzzle",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Puzzle 2026 games, Best, Best Games, Brain, Hypercasual, Puzzle",
    "description": "Test your strength and timing in Rope Push Game! Control the rope and push your opponent toward the edge of the arena. Pull and push at the right moment, maintain your balance, and use smart moves to gain the advantage. Reach the winning point and overcome increasingly challenging opponents.",
    "instructions": "Mouse click or tap to play",
    "url": "https://html5.gamemonetize.co/g6mfkfrja0qeptcd1xy5fiwv4xxtklwd/",
    "thumbnail": "https://img.gamemonetize.com/g6mfkfrja0qeptcd1xy5fiwv4xxtklwd/512x384.jpg",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gm-85551",
    "providerId": "85551",
    "title": "Crazy Bus Escape Runner",
    "category": "Arcade",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Arcade 3D, Action, Casual, Mobile, Obstacle, Skill, Stickman",
    "description": "Lead a fearless crowd through chaotic city roads in Crazy Bus Escape Runner. Swipe or use the keyboard to dodge dangerous obstacles, recruit new runners, survive brutal traps, and reach the finish together. Complete five increasingly challenging stages, protect your team, and prove you can escape every frantic course alive.",
    "instructions": "Click or tap to start Hold and drag left or right to steer on touch devices On desktop use A D or the Left Right Arrow keys Recruit runners avoid traps keep the leader alive and reach the finish Choose NEXT to continue or RESTART after failing",
    "url": "https://html5.gamemonetize.co/tktierqxsemt0iifx5x9had63otarsz0/",
    "thumbnail": "https://img.gamemonetize.com/tktierqxsemt0iifx5x9had63otarsz0/512x384.jpg",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gm-86069",
    "providerId": "86069",
    "title": "CAR SMASH OBBY 3D",
    "category": "Racing",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Racing Car, destruction, Driving, Obstacle, Physics, Stunts",
    "description": "Smash barriers, dodge giant traps and reach the finish in a car that can fall apart! Conquer 36 obstacle courses across six colorful worlds. Time your run past swinging hammers and crushers, jump gaps and escape giant rollers. Earn coins, collect 10 vehicles and upgrade impact power, speed, armor, grip and suspension. Checkpoints and quick retries keep every attempt short and exciting. Boost into barriers for stronger impacts. Play on desktop or mobile in 10 languages.",
    "instructions": "Auto acceleration A D or Left Right steer W Up Space boost S Down brake R checkpoint Escape pause Mobile hold the right-side arrows to steer and the lightning button above them to boost",
    "url": "https://html5.gamemonetize.co/akpoe15y02690iqssyoqm6dpotmcpuxl/",
    "thumbnail": "https://img.gamemonetize.com/akpoe15y02690iqssyoqm6dpotmcpuxl/512x384.jpg",
    "orientation": "landscape",
    "width": 1280,
    "height": 720
  },
  {
    "id": "gm-86073",
    "providerId": "86073",
    "title": "Car Obby 3D",
    "category": "Racing",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Racing Car, Collecting, Driving, Jumping, Obstacle, WebGL",
    "description": "Drive a tiny car across 12 floating obstacle courses in Car Obby 3D. Dodge swinging hammers, spinning obstacles and moving platforms, collect coins and reach checkpoints above the clouds. Unlock eight car designs or buy boosts: Ghost for 3 seconds, Nitro for 5 seconds, Jump and Flight for 5 seconds. Tap your stored boosts while driving. Recover from falls at checkpoints and improve your best times. Play with keyboard controls on desktop or one-hand steering and automatic acceleration on mobile. Includes 11 languages and saved progress.",
    "instructions": "Desktop W Up accelerate S Down brake and reverse A D or Left Right steer Space brake R reset Esc pause Mobile automatic acceleration drag left right on the thumb pad to steer and down to brake Tap a purchased boost to use it",
    "url": "https://html5.gamemonetize.co/0hbbm274a3v134mfpe2z7cgjy6ylxsji/",
    "thumbnail": "https://img.gamemonetize.com/0hbbm274a3v134mfpe2z7cgjy6ylxsji/512x384.jpg",
    "orientation": "landscape",
    "width": 1280,
    "height": 720
  },
  {
    "id": "gm-85975",
    "providerId": "85975",
    "title": "Bum Brawl Heaven",
    "category": "Action",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Adventure Action, Brawl, Fight, Fighting",
    "description": "Brawl through five heavenly locations against sixty angels in Bum Brawl: Heaven. Battle runners, sentinels, and scribes, collect power-ups, and unleash your halo special.",
    "instructions": "WASD ARROWS MOVE middot J PUNCH middot K KICK middot L HALO middot SPACE JUMP",
    "url": "https://html5.gamemonetize.co/afn4dij4qfblxysmsbbok007o2jxkmwq/",
    "thumbnail": "https://img.gamemonetize.com/afn4dij4qfblxysmsbbok007o2jxkmwq/512x384.jpg",
    "orientation": "landscape",
    "width": 960,
    "height": 600
  },
  {
    "id": "gm-86150",
    "providerId": "86150",
    "title": "Doomfront Iron Breach",
    "category": "Action",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Shooting 3D, 3D Games, First Person Shooter, Shoot, Shoot 'Em Up, Shooter, Shooting",
    "description": "Fight through industrial bunkers, badlands, a spaceport, and the Overlords fortress in Doomfront: Iron Breach, a sci-fi first-person shooter with six enemy types, five animated weapons, and five expansive sectors.",
    "instructions": "Mouse click or tap to play",
    "url": "https://html5.gamemonetize.co/t34z5o1hxwvn0fzanw148uxis4ix8b7p/",
    "thumbnail": "https://img.gamemonetize.com/t34z5o1hxwvn0fzanw148uxis4ix8b7p/512x384.jpg",
    "orientation": "landscape",
    "width": 960,
    "height": 600
  },
  {
    "id": "gm-86605",
    "providerId": "86605",
    "title": "Robotu Rebellion",
    "category": "Action",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Adventure Battle, Escape, Robot, Shooting",
    "description": "**Robotu Rebellion** is an action-packed puzzle escape game where you control a robot trapped inside a dangerous factory. Avoid deadly lasers, mechanical traps, and hostile security robots while searching for a way out. Discover hidden paths, solve security puzzles, and hack machines to overcome obstacles. Use stealth, strategy, and quick reflexes to survive the mechanical maze and escape the robot rebellion!",
    "instructions": "W S A D to move use mouse to attack",
    "url": "https://html5.gamemonetize.co/nbvkl1yokf7f1v1e64mcwjxt35h6vhqc/",
    "thumbnail": "https://img.gamemonetize.com/nbvkl1yokf7f1v1e64mcwjxt35h6vhqc/512x384.jpg",
    "orientation": "landscape",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "gm-86765",
    "providerId": "86765",
    "title": "Cosmetic Run",
    "category": "Arcade",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Arcade Adventure, Arcade, Girls, Makeover, running",
    "description": "Dash, blend, and buff your way to glory in Cosmetic Run! Play as fabulous makeup brushes and stylish runner girls racing through glamorous, high-stakes tracks. Dodge messy makeup spills, collect glowing highlighters, and create the ultimate beauty look before crossing the finish line in style. Web Dev https://www.crazygames.org.es/",
    "instructions": "Tap or hold click to move",
    "url": "https://html5.gamemonetize.co/nt4f4wm767onc1hr64eon89up2ywq4b2/",
    "thumbnail": "https://img.gamemonetize.com/nt4f4wm767onc1hr64eon89up2ywq4b2/512x384.jpg",
    "orientation": "portrait",
    "width": 350,
    "height": 600
  },
  {
    "id": "gm-86813",
    "providerId": "86813",
    "title": "Dark Hood",
    "category": "Arcade",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Arcade 1 Player, HTML5, Mobile, Puzzle",
    "description": "Dark Hood is a cute shadow-platform puzzler. Guide a tiny hooded blob through 70 dark levels, collect the stars and coins and reach the magic portal. A cozy adventure about a little creature who loves the darkness.",
    "instructions": "Arrow keys or on-screen buttons to move and jump",
    "url": "https://html5.gamemonetize.co/4pgw159hbufpab7obm7l2foyo2h4gq8i/",
    "thumbnail": "https://img.gamemonetize.com/4pgw159hbufpab7obm7l2foyo2h4gq8i/512x384.jpg",
    "orientation": "landscape",
    "width": 960,
    "height": 540
  },
  {
    "id": "gm-86711",
    "providerId": "86711",
    "title": "Ridge Racer 2D",
    "category": "Arcade",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Arcade Adventure, Arcade, Car, Driving, Unity3D, WebGL",
    "description": "Conquer unforgiving terrain in Ridge Racer 2D, a high-octane physics racer where precision throttle control meets rugged elevation. Balance momentum, upgrade custom vehicles, and master treacherous inclines across extreme off-road tracks to defy gravity, crush obstacles, and reach the peak before wiping out! Web Dev https://www.crazygames.com.es/",
    "instructions": "A and D or Left and Right to drive",
    "url": "https://html5.gamemonetize.co/ui4iefs3st4uup3vw9p77lyycacnxml9/",
    "thumbnail": "https://img.gamemonetize.com/ui4iefs3st4uup3vw9p77lyycacnxml9/512x384.jpg",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gm-86384",
    "providerId": "86384",
    "title": "Bike Obby Draw Pencil",
    "category": "Action",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Adventure 1 Player, 2026 games, 3D, 3D Games, Action, Adventure, Arcade, Mobile, roblox",
    "description": "Use your creativity and reflexes to complete the missing paths in 3D Side Platform Obby Draw Pencil! Draw paths with your pencil across the gaps between platforms to help your character move forward safely. Overcome different obstacles in each level, draw the right path, and reach the finish without falling. This fun adventure may look simple, but it requires focus, precision, and perfect timing. Get your pencil ready and draw your own path to victory!",
    "instructions": "Jump with W and move left and right using the A and D keys Mobile touch controls are also available",
    "url": "https://html5.gamemonetize.co/y6wq6n3z1bh9xf8lorl7uve5sz2d2uha/",
    "thumbnail": "https://img.gamemonetize.com/y6wq6n3z1bh9xf8lorl7uve5sz2d2uha/512x384.jpg",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gm-86751",
    "providerId": "86751",
    "title": "Resident Evil 4: 2.5D FPS",
    "category": "Action",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Shooting 2D, Action, First Person Shooter, Shoot, Shoot 'Em Up, Shooter, Shooting, Zombie",
    "description": "Enter the village. Survive five chapters of illustrated survival-horror action in Resident Evil 4: 2.5D FPS, an unofficial fan game.",
    "instructions": "Mouse click or tap to play",
    "url": "https://html5.gamemonetize.co/d9li5w4o71g2zws8dhdqb9r21egoak7z/",
    "thumbnail": "https://img.gamemonetize.com/d9li5w4o71g2zws8dhdqb9r21egoak7z/512x384.jpg",
    "orientation": "landscape",
    "width": 960,
    "height": 600
  },
  {
    "id": "gm-86122",
    "providerId": "86122",
    "title": "Geometry Vibes X Arrow",
    "category": "Arcade",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Arcade 2 Player, 2 Player Games, Arcade, arrow, Geometry",
    "description": "Geometry Vibes X Arrow is the newest evolution of the Geometry Vibes series, offering the most refined, competitive and customizable arrow experience so far. The goal is simple but demanding: guide your arrow through dangerous geometric paths, survive increasingly difficult patterns and reach the portal at the end of each route without touching anything. Every tap changes your altitude, every obstacle tests your timing and every mode challenges your mastery in different ways.",
    "instructions": "Click MOUSE Left Click or press SPACE to accelerate upward Release the button to move downward In multiplayer the additional players use H L and the Up Arrow Touch controls are supported on phones and tablets",
    "url": "https://html5.gamemonetize.co/z1f0avym9sh561rg8yu3hlmzy2u2zuvx/",
    "thumbnail": "https://img.gamemonetize.com/z1f0avym9sh561rg8yu3hlmzy2u2zuvx/512x384.jpg",
    "orientation": "landscape",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "gm-86760",
    "providerId": "86760",
    "title": "Hellforge: Demon Protocol",
    "category": "Action",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Shooting 2D, Action, Monster, Platform, Shooter, Shooting, Side Scrolling, trap, weapons",
    "description": "Hellforge: Demon Protocol is a 2D side-scrolling run-and-gun campaign with 20 industrial missions and progressive difficulty. Fight patrol soldiers, shield troops, gatling brutes, mech hounds and berserkers. Survive 16 trap types, discover secret pickups, collect six weapons, armor, grenades and shields, and defeat ten animated bosses that return as elite enemies in later levels. Checkpoints, three lives, dodging and two weapon slots reward skillful play. Web Dev https://www.poki.com.es/",
    "instructions": "Move A D or Left Right arrows Jump or double jump Space W or Up Aim mouse Fire left click or J Pick up use E Switch weapons Q or 1 2 Reload R Dodge Shift Grenade G Shield F Pause P or Esc Touch controls appear on mobile devices",
    "url": "https://html5.gamemonetize.co/qbflb7jktdwh6xibtrub9u3pb6u3g5h6/",
    "thumbnail": "https://img.gamemonetize.com/qbflb7jktdwh6xibtrub9u3pb6u3g5h6/512x384.jpg",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  },
  {
    "id": "gm-86706",
    "providerId": "86706",
    "title": "Mag Roller",
    "category": "Arcade",
    "engine": "gamemonetize",
    "provider": "GameMonetize",
    "art": 0,
    "tag": "NEW",
    "meta": "Arcade Adventure, Arcade, Ball, Fun, Unity3D, WebGL",
    "description": "Take control of Mag-Roller, a high-velocity magnetic sphere that pulls nearby cubes into its orbit. Roll through chaotic levels, build massive block armor on the fly, crush obstacles, and harness electromagnetic force to clear every stage in a satisfaction-filled path of devastation! Web Dev https://www.poki.org.es/",
    "instructions": "WASD or Arrow keys to move",
    "url": "https://html5.gamemonetize.co/xsdhcwwkr1v7xhzx661raou0zmcdf9df/",
    "thumbnail": "https://img.gamemonetize.com/xsdhcwwkr1v7xhzx661raou0zmcdf9df/512x384.jpg",
    "orientation": "landscape",
    "width": 800,
    "height": 600
  }
];
