/* Original Playnova mini-games. No external game services or trackers. */
'use strict';
window.PlaynovaGames = (() => {
  function lifecycle(ctx) {
    const controller = new AbortController(); let alive=true; const timers=[];
    return {on:(el,event,fn,opts={})=>el.addEventListener(event,fn,{...opts,signal:controller.signal}),
      later:(fn,ms)=>{const id=setTimeout(()=>{if(alive)fn()},ms);timers.push(id);return id},
      get alive(){return alive},destroy(){alive=false;controller.abort();timers.forEach(clearTimeout);ctx.area.replaceChildren()}};
  }
  function controls(ctx,life,labels,callback){const box=document.createElement('div');box.className='touch-controls';labels.forEach(([symbol,val])=>{const b=document.createElement('button');b.textContent=symbol;b.ariaLabel='Move '+val;life.on(b,'pointerdown',e=>{e.preventDefault();callback(val)});box.append(b)});ctx.area.append(box)}
  function canvasGame(ctx,type){
    const life=lifecycle(ctx),c=document.createElement('canvas');c.width=640;c.height=400;c.ariaLabel=type==='drift'?'Neon Drift racing game':type==='snake'?'Neon Snake game':'Orbit Breaker game';ctx.area.append(c);const g=c.getContext('2d');
    let paused=false,over=false,score=0,last=performance.now(),acc=0,elapsed=0,raf;
    let lane=1,obstacles=[],nextCar=.7,snake=[{x:9,y:6},{x:8,y:6},{x:7,y:6}],dir={x:1,y:0},queued=dir,food={x:15,y:6};
    let paddle=280,ball={x:320,y:290,vx:175,vy:-190},bricks=Array.from({length:40},(_,i)=>({x:37+(i%10)*57,y:35+Math.floor(i/10)*24,w:51,h:16,on:true}));
    const colors=['#b784ff','#c77eff','#ed78b8','#fbae86'];
    const move=(key)=>{if(over)return;if(type==='drift'){if(key==='left')lane=Math.max(0,lane-1);if(key==='right')lane=Math.min(2,lane+1)}else if(type==='snake'){const d={left:{x:-1,y:0},right:{x:1,y:0},up:{x:0,y:-1},down:{x:0,y:1}}[key];if(d&&(d.x!==-dir.x||d.y!==-dir.y))queued=d}else {if(key==='left')paddle=Math.max(0,paddle-40);if(key==='right')paddle=Math.min(550,paddle+40)}};
    const keys=new Set();life.on(document,'keydown',e=>{const map={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down'};if(map[e.key]){e.preventDefault();if(!e.repeat||type==='breakout')move(map[e.key]);keys.add(map[e.key])}if(e.code==='Space'){e.preventDefault();ctx.togglePause()}});life.on(document,'keyup',e=>{keys.clear()});life.on(window,'blur',()=>{keys.clear();if(!paused&&!over)ctx.togglePause()});
    life.on(c,'pointermove',e=>{if(type==='breakout'){const r=c.getBoundingClientRect();paddle=Math.max(0,Math.min(550,(e.clientX-r.left)*640/r.width-45))}});
    let sx=0,sy=0;life.on(c,'pointerdown',e=>{sx=e.clientX;sy=e.clientY;if(type==='drift')move(e.offsetX<c.clientWidth/2?'left':'right')});life.on(c,'pointerup',e=>{if(type==='snake'){const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))>10)move(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up')}});
    controls(ctx,life,type==='snake'?[['←','left'],['↑','up'],['↓','down'],['→','right']]:[['←','left'],['→','right']],move);
    function end(message){over=true;ctx.status(message+' Press Restart for another round.');draw()}
    function background(){g.fillStyle='#0b1020';g.fillRect(0,0,640,400);g.strokeStyle='#1d2843';g.lineWidth=1;for(let x=0;x<640;x+=20){g.beginPath();g.moveTo(x,0);g.lineTo(x,400);g.stroke()}for(let y=0;y<400;y+=20){g.beginPath();g.moveTo(0,y);g.lineTo(640,y);g.stroke()}}
    function rounded(x,y,w,h,color,r=7){g.fillStyle=color;g.beginPath();g.roundRect(x,y,w,h,r);g.fill()}
    function car(x,y,color){rounded(x,y,40,66,color,8);rounded(x+6,y+11,28,16,'#15253e',4);rounded(x+7,y+44,26,10,'#1a2f47',3);g.fillStyle='#fff3ad';g.fillRect(x+4,y+2,8,4);g.fillRect(x+28,y+2,8,4)}
    function draw(){background();if(type==='drift'){g.fillStyle='#151a2e';g.fillRect(168,0,304,400);g.strokeStyle='#9068e5';g.lineWidth=3;[168,472].forEach(x=>{g.beginPath();g.moveTo(x,0);g.lineTo(x,400);g.stroke()});g.strokeStyle='#566185';g.setLineDash([22,25]);g.lineDashOffset=-elapsed*150;[270,370].forEach(x=>{g.beginPath();g.moveTo(x,0);g.lineTo(x,400);g.stroke()});g.setLineDash([]);obstacles.forEach(o=>car(200+o.lane*100,o.y,'#ed78b8'));car(200+lane*100,314,'#c7fb65');g.fillStyle='#6f7a9d';g.font='12px monospace';g.fillText('NEON CITY',25,30);g.fillText('STAY IN YOUR FLOW',485,375)}else if(type==='snake'){rounded(food.x*20+2,food.y*20+2,16,16,'#fc7aa9');snake.forEach((s,i)=>rounded(s.x*20+1,s.y*20+1,18,18,i===0?'#dafa93':'#8dda6e',4));const head=snake[0];g.fillStyle='#142521';g.fillRect(head.x*20+5,head.y*20+5,3,3);g.fillRect(head.x*20+12,head.y*20+5,3,3)}else{bricks.filter(b=>b.on).forEach(b=>rounded(b.x,b.y,b.w,b.h,colors[Math.floor((b.y-35)/24)],4));rounded(paddle,365,90,12,'#78f2e0',6);g.shadowBlur=17;g.shadowColor='#c7fb65';g.fillStyle='#c7fb65';g.beginPath();g.arc(ball.x,ball.y,7,0,Math.PI*2);g.fill();g.shadowBlur=0}
      if(paused||over){g.fillStyle='#070b19ba';g.fillRect(0,0,640,400);g.textAlign='center';g.fillStyle='#f3f6ff';g.font='bold 34px system-ui';g.fillText(over?'Nice run!':'Paused',320,180);g.fillStyle='#c7fb65';g.font='18px system-ui';g.fillText(over?'Score: '+score:'Press Resume to keep playing',320,218);g.textAlign='left'}
    }
    function tick(now){if(!life.alive)return;const dt=Math.min((now-last)/1000,.04);last=now;if(!paused&&!over){elapsed+=dt;if(type==='drift'){nextCar-=dt;const speed=150+Math.min(140,elapsed*3);if(nextCar<=0){obstacles.push({lane:Math.floor(Math.random()*3),y:-75});nextCar=Math.max(.63,1.05-elapsed*.006)}obstacles.forEach(o=>{o.y+=speed*dt;if(o.lane===lane&&o.y+60>319&&o.y<373)end('Traffic caught you!')});obstacles=obstacles.filter(o=>o.y<420);const n=Math.floor(elapsed*10);if(n!==score&&!over){score=n;ctx.score(score)}}else if(type==='snake'){acc+=dt;if(acc>.125){acc=0;dir=queued;const head={x:snake[0].x+dir.x,y:snake[0].y+dir.y},eat=head.x===food.x&&head.y===food.y;const body=eat?snake:snake.slice(0,-1);if(head.x<0||head.x>=32||head.y<0||head.y>=20||body.some(s=>s.x===head.x&&s.y===head.y)){end('Watch the walls and your tail.')}else{snake.unshift(head);if(eat){score+=10;ctx.score(score);if(snake.length===640){end('You filled the entire board!')}else{do{food={x:Math.floor(Math.random()*32),y:Math.floor(Math.random()*20)}}while(snake.some(s=>s.x===food.x&&s.y===food.y))}}else snake.pop()}}}else{if(keys.has('left'))paddle=Math.max(0,paddle-300*dt);if(keys.has('right'))paddle=Math.min(550,paddle+300*dt);ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(ball.x<7){ball.x=7;ball.vx=Math.abs(ball.vx)}if(ball.x>633){ball.x=633;ball.vx=-Math.abs(ball.vx)}if(ball.y<7){ball.y=7;ball.vy=Math.abs(ball.vy)}if(ball.vy>0&&ball.y+7>=365&&ball.y<382&&ball.x>=paddle-7&&ball.x<=paddle+97){ball.y=357;ball.vy=-Math.abs(ball.vy);ball.vx=(ball.x-(paddle+45))*5}for(const b of bricks){if(b.on&&ball.x+7>b.x&&ball.x-7<b.x+b.w&&ball.y+7>b.y&&ball.y-7<b.y+b.h){b.on=false;ball.vy*=-1;score+=25;ctx.score(score);break}}if(ball.y>412)end('The ball slipped past.');if(bricks.every(b=>!b.on))end('Perfect clear!')}}draw();raf=requestAnimationFrame(tick)}
    ctx.status(type==='drift'?'Use ← → or tap either side to change lanes.':type==='snake'?'Arrow keys, swipe, or use the buttons below.':'Move your pointer or use ← → to control the paddle.');raf=requestAnimationFrame(tick);
    return {pause(){paused=!paused;last=performance.now();draw();return paused},destroy(){cancelAnimationFrame(raf);life.destroy()}};
  }
  function merge(ctx){const life=lifecycle(ctx);let board=Array(16).fill(0),score=0,ended=false;const el=document.createElement('div');el.className='board2048';el.ariaLabel='2048 game board';ctx.area.append(el);function spawn(){const empty=board.flatMap((n,i)=>n?[]:[i]);if(empty.length)board[empty[Math.floor(Math.random()*empty.length)]]=Math.random()<.9?2:4}function draw(){el.innerHTML=board.map(n=>`<div class="tile" data-v="${n}">${n||''}</div>`).join('')}function move(d){if(ended)return;const old=board.join();for(let a=0;a<4;a++){const ids=Array.from({length:4},(_,b)=>d==='left'?a*4+b:d==='right'?a*4+3-b:d==='up'?b*4+a:(3-b)*4+a);let vals=ids.map(i=>board[i]).filter(Boolean),out=[];for(let i=0;i<vals.length;i++){if(vals[i]===vals[i+1]){out.push(vals[i]*2);score+=vals[i]*2;i++}else out.push(vals[i])}while(out.length<4)out.push(0);ids.forEach((id,i)=>board[id]=out[i])}if(board.join()!==old){spawn();draw();ctx.score(score)}if(!board.includes(0)&&board.every((v,i)=>(i%4===3||v!==board[i+1])&&(i>=12||v!==board[i+4]))){ended=true;ctx.status('No moves left. Your score: '+score+'. Restart to try again.')}else if(board.includes(2048))ctx.status('You made 2048! Keep going for an even bigger tile.')}
    life.on(document,'keydown',e=>{const map={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'};if(map[e.key]){e.preventDefault();move(map[e.key])}});let x,y;life.on(el,'pointerdown',e=>{x=e.clientX;y=e.clientY;el.setPointerCapture(e.pointerId)});life.on(el,'pointerup',e=>{const dx=e.clientX-x,dy=e.clientY-y;if(Math.max(Math.abs(dx),Math.abs(dy))>15)move(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up')});controls(ctx,life,[['←','left'],['↑','up'],['↓','down'],['→','right']],move);spawn();spawn();draw();ctx.status('Combine matching tiles. Can you reach 2048?');return life;
  }
  function memory(ctx){const life=lifecycle(ctx),symbols=['✦','☀','☾','♠','♥','◆','♣','♫'];let deck=[...symbols,...symbols];for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}let open=[],matched=new Set(),moves=0,locked=false;const board=document.createElement('div');board.className='memory-board';ctx.area.append(board);deck.forEach((symbol,i)=>{const b=document.createElement('button');b.className='memory-tile';b.textContent='✧';b.ariaLabel='Reveal card '+(i+1);life.on(b,'click',()=>{if(locked||matched.has(i)||open.includes(i))return;b.textContent=symbol;b.classList.add('flipped');b.ariaLabel='Card '+(i+1)+': '+symbol;open.push(i);if(open.length===2){moves++;const [a,c]=open;if(deck[a]===deck[c]){matched.add(a);matched.add(c);[a,c].forEach(n=>board.children[n].classList.add('matched'));open=[];ctx.score(Math.max(0,matched.size/2*100-(moves-matched.size/2)*5));ctx.status(matched.size===16?'All pairs found in '+moves+' moves!':'Pairs '+matched.size/2+'/8 · Moves '+moves)}else{locked=true;life.later(()=>{open.forEach(n=>{board.children[n].classList.remove('flipped');board.children[n].textContent='✧';board.children[n].ariaLabel='Reveal card '+(n+1)});open=[];locked=false;ctx.status('Pairs '+matched.size/2+'/8 · Moves '+moves)},800)}}});board.append(b)});ctx.status('Find all eight pairs with as few moves as possible.');return life}
  function reaction(ctx){const life=lifecycle(ctx);const b=document.createElement('button');b.className='reaction';b.innerHTML='Ready when you are.<small>Tap to begin the reaction test.</small>';ctx.area.append(b);let state='idle',timer,start,attempt=0,results=[];function wait(){state='waiting';b.className='reaction';b.innerHTML='Wait for green…<small>Stay focused. Don’t tap yet.</small>';timer=life.later(()=>{state='ready';start=performance.now();b.className='reaction ready';b.innerHTML='TAP NOW!<small>Go, go, go.</small>'},1300+Math.random()*2600)}life.on(b,'click',()=>{if(state==='idle'||state==='result'){wait()}else if(state==='waiting'){clearTimeout(timer);state='idle';b.innerHTML='A little too soon!<small>Tap to try again.</small>';ctx.status('Wait until the panel turns green.')}else if(state==='ready'){const ms=Math.round(performance.now()-start);results.push(ms);attempt++;ctx.score(ms);state='result';b.className='reaction';b.innerHTML=ms+' ms<small>Tap for another round.</small>';ctx.status('Round '+attempt+' · Average '+Math.round(results.reduce((a,c)=>a+c,0)/results.length)+' ms · Lower is better.')}});ctx.status('Test your reflexes. Your fastest reaction is saved.');return life}
  function tic(ctx){const life=lifecycle(ctx);let board=Array(9).fill(''),turn='X',over=false;const el=document.createElement('div');el.className='tic-board';ctx.area.append(el);board.forEach((_,i)=>{const b=document.createElement('button');b.ariaLabel='Square '+(i+1);life.on(b,'click',()=>{if(over||board[i])return;board[i]=turn;b.textContent=turn;b.classList.toggle('o',turn==='O');b.ariaLabel='Square '+(i+1)+': '+turn;const won=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(line=>line.every(n=>board[n]===turn));if(won){over=true;ctx.score(100);ctx.status(turn+' wins! Restart for a rematch.')}else if(board.every(Boolean)){over=true;ctx.status('A draw. You’re both too good!')}else{turn=turn==='X'?'O':'X';ctx.status(turn+'’s turn · Pass the device to your friend.')}});el.append(b)});ctx.status('X goes first. Two players, one device.');return life}
  function slide(ctx){const life=lifecycle(ctx);let board=[1,2,3,4,5,6,7,8,0],moves=0,over=false;const neighbors=i=>[i-3,i+3,...(i%3?[i-1]:[]),...(i%3<2?[i+1]:[])].filter(n=>n>=0&&n<9);let prev=-1;for(let k=0;k<100;k++){const z=board.indexOf(0),ns=neighbors(z).filter(n=>n!==prev),n=ns[Math.floor(Math.random()*ns.length)];[board[z],board[n]]=[board[n],board[z]];prev=z}if(board.every((v,i)=>v===(i+1)%9))[board[7],board[8]]=[board[8],board[7]];const el=document.createElement('div');el.className='slide-board';ctx.area.append(el);function draw(){el.replaceChildren();board.forEach((v,i)=>{const b=document.createElement('button');b.textContent=v||'';b.className=v?'':'blank';b.ariaLabel=v?'Move tile '+v:'Empty square';b.disabled=!v||over;life.on(b,'click',()=>{const z=board.indexOf(0);if(!neighbors(z).includes(i)||over)return;[board[z],board[i]]=[board[i],board[z]];moves++;if(board.every((v,n)=>v===(n+1)%9)){over=true;ctx.score(Math.max(10,1000-moves*5));ctx.status('Solved in '+moves+' moves!')}else ctx.status('Moves: '+moves+' · Arrange 1–8 with the empty square last.');draw()});el.append(b)})}draw();ctx.status('Slide the tiles into order, from 1 to 8.');return life}
  return {drift:ctx=>canvasGame(ctx,'drift'),breakout:ctx=>canvasGame(ctx,'breakout'),snake:ctx=>canvasGame(ctx,'snake'),merge,memory,reaction,tic,slide};
})();
